### ISSUE TITLE
Closed Programs ~ Listing wrong date for "case becomes intake again on ..."

### ISSUE THREAD

**Issue by ALJ10** [MN-Script-Team/DHS-MAXIS-Scripts#1045]
Per a few financial workers here: 
Script: Closed Programs

I selected Cash but changed it to GA/GRH

The case note:

---Closed GA/GRH 8/31/2015---                                             
 * Reason for closure: Client failed to file for other benefits SSI/RSDI,  
                       GA/GRH closed for 09/15.                            
 ---                                                                       
 * Last cash REIN date: 8/31/2015, after which a new CAF is required.      
 * All programs closed. Case becomes intake again on 10/1/2015.            
 ---                                                                       
 en                                                                        

The case becomes intake again 09/01/2015 if the last rein date is 08/31/2015.

**Comment by CDPotter** [comment]
Currently there is no code in the state supported script that would write "GA/GRH" into the case note, so either the agency is running custom code, or someone adjusted the case note to say that. If the script code has been manually modified then it would need to be adjusted by the agency that modified it, or a fix that would apply across all agencies submitted to github. 

Typically for GA/GRH agencies hold onto the case for a month before transferring it to CLS so that is why the date calculation reads as such.

**Comment by theVKC** [comment]
@ALJ10, I'm tagging this as "won't fix" because your users manually modified the selection. If you'd like to ask that functionality be included to separate GA/GRH logic from the rest of the cash logic, we can do that, but it's a separate issue, really. Does that make sense? Closing this one because the user manually intervened after-the-fact.

**Comment by ALJ10** [comment]
Understandable! Here's the response I rec'd from the supervisor: I am reading this as they are not clear that the case becomes intake date should be 09/01/15 not 10/01/15, however CDPotter stated that most agencies hold the case for a month before transferring to CLS  so it sounds as though they have the wording that way because of that. I would be interested to know if they could enhance the script to include a check box that the worker can select asking if they want it to become intake on 09/01/15 or 10/01/15 (for example) that way the agency can choose per their internal procedures. 

Please let me know if this could be reconsidered for the issue with the wrong date being listed or if it should be considered an enhancement request to possibly add a checkbox. Thank you!

**Comment by theVKC** [comment]
Unfortunately this sort of additional checkbox may go against policy for non GA/GRH cash cases, and the script at present does not (as I recall) contain logic to flesh those out. So, folks could inadvertently use it in the wrong case (MFIP for instance) and cause headaches.

I think I mentioned this above, but if GA/GRH logic were separated out, I could clarify the preferred policy with DHS folks and then we could standardize it. Generally speaking, we don't really allow much in the way of county-specific enhancements, because I only get about 5 hours per week to program scripts (I'm the only one at DHS), and typically bug fixes and statewide enhancements have to come first. If a new request were made to explore different logic for GA/GRH cases statewide, I would be happy to consider adding that to the list.
