### ISSUE TITLE
Dail Scrubber scripts no longer direct navigating?

### ISSUE THREAD

**Issue by MelissaFox-Stearns** [MN-Script-Team/DHS-MAXIS-Scripts#1221]
Previously when we would run the dail scrubber and it finished doing its thing, we would PF3 and this would take us back to the Dails so it could be deleted and go onto the next one. 
Now when the script ends,  the PF3 goes to the Self menu instead so the worker has to enter dail/dail each time. I have noticed this on the CS Dail and Bndx scrubbers so far. 

Can we get this to go back to the Dail for the current case like it used to?

**Comment by theVKC** [comment]
Hey @IlseFerris, wondering if this is Doubtfire related. Did you replace the "s" and "n" that was entered on the DAIL with direct navigation? That might have messed with the flow that workers normally do. Surprised nobody caught that in beta testing, it was out for a full week.

**Comment by IlseFerris** [comment]
https://github.com/MN-Script-Team/DHS-MAXIS Scripts/commit/404483e5133ca17428f0ae4a5a88f23dcc61e793
Here's the link to the changes I made for Doubtfire.  

BNDX: only change was the FuncLib line.  

CS REPORTED NEW EMPLOYER: I replaced and ERRR message with a "navigate_to_MAXIS_screen("STAT", MEMB")"

CSES PROCESSING: only change was the FuncLib line

**Comment by C-Love** [comment]
@theVKC I think I need to make a bit of an argument for this being a bug. Ramsey County users experienced a HUGE decrease in efficiency with this change. Processing the large number of CSES DAILS on the case loads slowed their work immensely with this navigation issue. There was a large outcry.

**Comment by RobertFewins-Kalb** [comment]
I can take on fixing this. I made the most recent update and I can have it navigate back to DAIL/DAIL for that client.

**Comment by RobertFewins-Kalb** [comment]
Brief synopsis of my update: Doubtfire update include a navigate_to_MAXIS_screen, but it was not gathering the case number so it did not work. Utilizing navigate_to_MAXIS_screen, however, also requires the script to go back to SELF, which is why it is going back to SELF when you PF3 from case note, whereas, before, the script was navigating through the case directly from DAIL/DAIL, which is why it would return to DAIL/DAIL when you would PF3 out of the case note.

So far as I could tell, the only reason navigate_to_MAXIS_screen was added was to get around ERRR, but that's an easy fix...
row = 1
col = 1
EMSearch "ERRR", row, col
IF row <> 0 THEN transmit

Then we can remove the navigate_to_MAXIS_screen and have the script return to its previous functionality. We've been getting complaints in Anoka County as well.

**Comment by RobertFewins-Kalb** [comment]
Or, I suppose, just this...

![image](https://cloud.githubusercontent.com/assets/7842016/10463929/e712a3e4-71ac-11e5-86d8-628dd6206164.png)

**Comment by C-Love** [comment]
@RobertFewins-Kalb That looks like it would fix it for the CS REPORTED NEW EMPLOYER.
Workers are saying the issue is when Processing Disbursements as well. In fact the worker says that she used to use the 'View/Pick Selection' function on DAIL to have only CS DAILs viewed and when the script finished that maintained the Selection she had. 

I see on line 296 that there is a 'navigate_to_MAXIS_screen' function - that backs to SELF and would lose the DAIL anchor. We could PF3 at that point to get back to DAIL and then navigate from there to STAT/MEMB. Not sure if there is any other function that might cause that DAIL anchor to be lost.

**Comment by MelissaFox-Stearns** [comment]
@theVKC @C-Love @RobertFewins-Kalb 

CS Dails came out today. Am I the only one where it's still going back to Self instead of Dail/Dail?

**Comment by RobertFewins-Kalb** [comment]
It looks like it should always navigate back to SELF because of the navigate_to_MAXIS_screen function call

**Comment by theVKC** [comment]
I think @C-Love replaced that though. I pulled it in myself. Could you be on the beta branch?

**Comment by MelissaFox-Stearns** [comment]
Somebody must have done something because it's working like a boss now!

**Comment by theVKC** [comment]
You-all are using the beta branch. I hadn't updated the beta branch. Hence, you didn't have the fix. I forget that there are counties where everyone uses beta.
