### ISSUE TITLE
DAIL scrubber: update MEMI panel with cit/id response

### ISSUE THREAD

**Issue by IlseFerris** [MN-Script-Team/DHS-MAXIS-Scripts#1250]
Request from Hennepin County user: "It would also be nice if the (MEMI CIT/ID DAIL) scrubber (case noted) then went into memi maxis panel & changed Citizenship Ver to OT(other) for this DAIL message: “MEMI: CITIZENSHIP HAS BEEN VERIFIED THROUGH SSA”

**Comment by theVKC** [comment]
I'm actually not sure if this is policy correct. Why am I thinking we need the worker to do this manually? Anyone care to take it up with HC policy? It could be a bit before I can reach out.

**Comment by IlseFerris** [comment]
I'm checking into this. Standby...

**Comment by theVKC** [comment]
Can I bump this @IlseFerris? How's it going? Care to share?

**Comment by IlseFerris** [comment]
Last I heard was 9 days ago from a HC contact at DHS. I have a feeling this one might be in purgatory for a while until we hear an answer.  Go ahead and close the issue. I will manually track it for a response and re-post if applicable.

**Comment by theVKC** [comment]
Great!

**Comment by theVKC** [comment]
Reopened because @IlseFerris heard from DHS HC on this. She'll elaborate.

**Comment by theVKC** [comment]
Marking this as help-wanted because @IlseFerris may not have a lot of time in the near future to work on it.

**Comment by CDPotter** [comment]
I'll work on this.

**Comment by CDPotter** [comment]
Alright, changed this one rather radically so before I pull I wanted to get opinions. While thinking things out I had trouble figuring out how the script would find the correct person's memi panel to update. The worker has the ability to change the names in the dialog and then there's also the problem of people with the same name in the HH(a problem I know all to well). It just seemed difficult and cumbersome to try to find the correct person to update. Then it struck me. Since the case note is basically the same for everyone and everyone's memi is gonna get updated with "OT" why not make use of the HH member dialog. So here are the results. You run the script on the dail, it brings up the HH member dialog. You select the people you've received the DAIL on. You hit ok. Then it updates memi (actual date of today) with OT, then asks for worker signature(dialog format so update worker sig will autofull), then you get this case note. 

![2015-12-17 09_10_40-s1 - anoka desktop - anoka scripted desktop - bluezone mainframe display](https://cloud.githubusercontent.com/assets/7841989/11873013/13dd44f0-a49e-11e5-8950-1fdc1cc3b5a6.png)

Thoughts?

After the cuts this puts the script down to 50 lines.

**Comment by theVKC** [comment]
I'd rather automate the HH member selection if we could.

Couldn't we scan MEMB for the right HH member? If I'm not mistaken, we have some "identification" stuff in the DAIL message that could be useful (details of which I don't want to share on GitHub).
