### ISSUE TITLE
Expedited Determination - Seperate Case Note

### ISSUE THREAD

**Issue by C-Love** [MN-Script-Team/DHS-MAXIS-Scripts#1264]
It has been suggested that once a SNAP interview is completed a separate case note that details exactly why or why not a case is expedited would help with our XFS QC numbers. Essentially workers are not clear enough in terms of their final assessment for expedited. 

I am thinking of this as a new script that will read some STAT panels and do some calculation - kind of a cross between CAF and Expedited Screening. Like a followup to Expedited Screening. Does this line up with what policy/ME is looking for? Do others think this would be helpful for workers?

**Comment by ruthmaloney** [comment]
When we look at expedited cases, we look for the following:

·         to see that the app was screened the same day it was received (within business hours),

·         whether the applicant was offered a same/next day interview,

·         whether the interview took place within 5 business days,

·         if a phone interview was offered,

·         if the worker requested more than just a form of ID for verifications (ID is the only requirement for expedited), and

·         if the calculations used in the expedited screening were correct at the time of application.

We will also be looking at the date stamp for 2016 reviews.

I think the expedited screening script covers most of these requirements and that there are other scripts to cover the interview date piece.

Ruth Maloney

**Comment by theVKC** [comment]
@C-Love, based on @ruthmaloney's point, do you want to leave the issue up?

**Comment by C-Love** [comment]
I guess I am conflicted on this point. We use the Expedited Screening script when an application is received and don't have anything but the CAF1 to go off of. More often than not this information is determined to be different once the interview is completed. The complicated cases and situations then seem to become a little unclear if something is screened as expedited but then in the course of the interview is determined to not be expedited (or vice versa). 

@ruthmaloney when reviewing the cases, if an application is screened as potentially expedited but Expedited SNAP is not approved based on the interview, how clear does that change need to be in case notes? I guess that is what I am hoping this script would address.

**Comment by ruthmaloney** [comment]
If the CAF script is used, the income and deductions reported on the script (and in MAXIS) should add the clarification needed to verify that the case is no longer expedited based on the interview and/or verifications. We don’t generally see these cases because we review cases that have been approved as expedited.

We frequently see the opposite situation – a case is screened as non-expedited (whether based off the CAF1 or an incorrect screening – not asking questions correctly or incorrect income/deduction calculations), then at the interview it’s determined that the case is expedited. We typically call these cases as an error unless something changed in the HH from the time of screening to the interview, such as a job ended unexpectedly. The case note needs to explain why expedited wasn’t processed correctly in these situations. I think the CAF script has a line/question that asks why expedited wasn’t approved timely. If the worker adds a note to this section, we will look to determine if it’s correct. Many times, it doesn’t fall into a correct category and there is still an error. An example I ran across yesterday was “worker was out of the office so couldn’t process expedited”.

Ruth Maloney

**Comment by theVKC** [comment]
@ruthmaloney, do you think we should allow a list of "approved" reasons expedited wasn't processed? Think that might help?

**Comment by C-Love** [comment]
I think that would be wonderful.

**Comment by theVKC** [comment]
Removed "question" and added it to the to-do for the Feb release. Is that cool, Casey?

**Comment by C-Love** [comment]
Yes - sounds good

**Comment by theVKC** [comment]
@C-Love: think this will be done by Friday? Script freeze starts Tuesday.

**Comment by C-Love** [comment]
Yes! I have a good start and time on Thursday. I want to get this done by then

**Comment by theVKC** [comment]
Beautiful. Thank you!!

**Comment by theVKC** [comment]
FYI, I'm waiting on #1828 for this update. If you can let me know when it's done (or if it won't be done this month), that would be super!
