### ISSUE TITLE
Bugs Reported on SIR -- NOTES - Application Received

### ISSUE THREAD

**Issue by RobertFewins-Kalb** [MN-Script-Team/DHS-MAXIS-Scripts#1315]
Application Received appears to have some bugs in the logic around the dialog, particularly as it applies to error checking and an ApplyMN being received.

**Comment by C-Love** [comment]
So, I tried to write this to be fairly automated and I had some workers listing these same issues. The case needs to be pending first because the date of application and the programs pending are being read off of MAXIS instead of being entered by the worker. What I read on the discussion board is that the date of application and programs are not listing in the case note. This happens when it is not pended first. I could write some error checking that if no pending programs are found, either the script will give a warning, or provide a way for the worker to manually enter the information.

Are you hitting different bug that this?

**Comment by C-Love** [comment]
The problem would also exist if the case was in PND1 status since programs aren't listed.

**Comment by theVKC** [comment]
@C-Love, are you working on this?

**Comment by C-Love** [comment]
Yes please. I want it.
