### ISSUE TITLE
DAIL scrubber NEW HIRE enhancement 

### ISSUE THREAD

**Issue by IlseFerris** [MN-Script-Team/DHS-MAXIS-Scripts#1413]
Request from Hennepin Co worker: Now that HC can be closed when a recipient doesn't respond to a new hire, can the script also update the HC pop up in CM + 1

**Comment by theVKC** [comment]
I'm hesitant because it would require the script to navigate ahead to the next month, which is really hard. Plus, I think policy might disagree with updating the pop-up right away, as it stops the stat edit that prohibits results (and we need to give time for this, I believe). I could be wrong about that last point, but the next month stuff is a huge thumbs down from me.

**Comment by CDPotter** [comment]
Agreed, I know we've had it requested in the past but policy concerns and difficulty of making sure that the job carried over to the next month (sometimes stat panels don't carry forward for whatever reasons) always proved to be road blocks.

**Comment by IlseFerris** [comment]
Sounds good. Thanks for the input. Closing the issue.
