### ISSUE TITLE
Standardize use of 7 digit (x1##### or PW#####) worker numbers across bulk scripts

### ISSUE THREAD

**Issue by RobertFewins-Kalb** [MN-Script-Team/DHS-MAXIS-Scripts#1434]
Misc Non-MAGI HC deductions is not properly dumping the user's x1 number In REPT/ACTV...
![image](https://cloud.githubusercontent.com/assets/7842016/11307396/6e028750-8f7d-11e5-967c-a66cbdb7bf7c.png)

However, we have noticed that the script does the exact same thing as BULK>> PDED (PDED came second...).

Proposal >> Fix position of worker_number dump in REPT/ACTV and update Misc Non-MAGI HC Deductions with functionality from BULK>> PDED (since there are additional fields being recorded in PDED script) and eliminate the PDED script (as they are rather redundant).

**Comment by theVKC** [comment]
You're talking about two separate issues: a bug and an enhancement.

Re: the bug: This logic needs to match the logic used in the other BULK scripts. I don't particularly care how the problem is solved (and I support solving it), so long as the logic all matches. If you've devised a new method, I want to hear it, but remember that some users of the script work across counties (so that same logic as used on PND2 and ACTV needs to remain intact).

Enhancement: please create a separate issue and update the title of this one.

Are you volunteering for this?

**Comment by theVKC** [comment]
@RobertFewins-Kalb: are you working on this? I'm at hackathon and we can look at it if it hasn't been evaluated.

**Comment by RobertFewins-Kalb** [comment]
I have not.

**Comment by CDPotter** [comment]
I was going to update the worker number bug on each script standardizing to a 7 digit format on all of them. Would you like that submitted script by script or in one big pull?

**Comment by theVKC** [comment]
Whatever easiest for you at this point. :)

**Comment by theVKC** [comment]
I've renamed the issue to reflect the new scope.
