### ISSUE TITLE
Appt letter Looping issue with cases in PND1 and month incorrect

### ISSUE THREAD

**Issue by khiestand** [MN-Script-Team/DHS-MAXIS-Scripts#1482]
I have a worker that is trying to use the Appointment letter script and it just keeps looping, she clicks ok and then it runs but she has to click the stop button to get it to stop.  I verified she is in S1 and she has opened and closed Bluezone a few times.  Anyone else having any issues?? @devonne01   I am leaving for the day at 2pm so tagged Devonne on this.

**Comment by theVKC** [comment]
I would think this would be largely reported as it's a popular script. Anyone in @MN-Script-Team/5k-club see it?

**Comment by RobertFewins-Kalb** [comment]
No complaints in x102 and when I test it, all it well.

**Comment by RobertFewins-Kalb** [comment]
*is well...

**Comment by IlseFerris** [comment]
My county does not use this script, so no input from the x127. Sorry.

**Comment by RobertFewins-Kalb** [comment]
scandal!!

**Comment by IlseFerris** [comment]
We're always causing trouble :)

**Comment by theVKC** [comment]
#StateOfHennepin #x127 #theydontbreaktherulestheyjustmakenewones

**Comment by IlseFerris** [comment]
LOL! It's funny because it's true

**Comment by StormageddonDLOA** [comment]
No issues when I used it earlier today. X173

**Comment by devonne01** [comment]
I think I have figured out but not sure why it is happening. It seems to happen in PND1 status for the appointment letter but can do other scripts. I moved one case to pnd2 and ran the appointment script and it worked then. That’s why I’m thinking it’s if the case is still in PND1 status? Any ideas?

**Comment by theVKC** [comment]
Hmmm. Is there a function in the script that checks PND2? If there is, perhaps we need to include logic to detect a case in PND1 and cancel that specific function?

**Comment by courtrightd** [comment]
I just ran it in training on a PND1 case without issue.

**Comment by devonne01** [comment]
Hmm.. I did both cases that my coworker had in pnd1 and I had issues on my computer. I then moved one to pnd2 and ran the appointment script again and had NO issues.

**Comment by theVKC** [comment]
@devonne01 and @courtrightd: can you tell me what version of BlueZone you're running? (Help menu>About BlueZone)? The standard deployment is v5.1c2.

**Comment by devonne01** [comment]
Does this help?

[cid:image001.png@01D12CF1.B4CBA340]

**Comment by courtrightd** [comment]
V5.1 Build 1266

**Comment by theVKC** [comment]
@devonne01, I can't see that because this is on GitHub. You're responding via email so I can't see attachments here on GitHub.

**Comment by devonne01** [comment]
OOPS sorry LOL 
Bluezone mainframe display v5.1 build 1266

**Comment by theVKC** [comment]
@devonne01 and @courtrightd: v5.1, or v5.1c2? There is a difference, and I need to confirm something.

**Comment by courtrightd** [comment]
My version is identical – V5.1 build 1266.   No c2 anywhere that I can see.

**Comment by RobertFewins-Kalb** [comment]
I'm curious what logic is looping. Are we talking about the script generating new case notes and appointment letters on a constant loop? We're not really working with a lot of information.

**Comment by devonne01** [comment]
I see any v5.1c2 it just says v5.1

**Comment by devonne01** [comment]
I have a coworker that has two cafs that she wanted to send out an appointment letter for in case notes. it's looping and I thought maybe it was because it was in pnd1 status because I tried one of hers and I had the same issue but when I moved it to pnd2, it let me make the appointment letter. She thinks it has to do with the footer months. She states she got applications in November and tried to do appointment letter in December and it didn't work but if she went back into the footer month of November it worked.

**Comment by theVKC** [comment]
Any ideas as to why that would be the case? Why would the footer month matter?

**Comment by courtrightd** [comment]
Apparently they do matter, I just recreated the issue in training once I did the footer month.  Stand by while I dig into this.

**Comment by courtrightd** [comment]
The issue is the maxis_background_check function.  If the script is run from 12/15 on a PND1 case and 11/15 is appl month, maxis generates an error message: “benefit month must equal application month for CAF I cases 11/15”  Stuck on the self screen, it becomes an infinite loop.  I’m thinking potential solution is to put the code for maxis background check directly into the script, add a check for the error message, and if found change the footer month and check for background again.
Thoughts?

**Comment by khiestand** [comment]
I knew something was "looping" infinitely! :-) I am so proud of myself for using the correct terminology!

**Comment by devonne01** [comment]
Good job. Kelly :)

**Comment by theVKC** [comment]
@courtrightd: I like your solution. Comment it well. :)
