### ISSUE TITLE
Approved programs grabbing unapproved

### ISSUE THREAD

**Issue by CDPotter** [MN-Script-Team/DHS-MAXIS-Scripts#1750]
So I was approving a change to a SNAP case that also has MSA. MSA wasn't changing so I didn't approve the result. However the new approved programs grabbed and case noted "* MSA for 02/16: $0.00" 

@C-Love did you change it so it doesn't check approval dates and look for "approved"?

**Comment by courtrightd** [comment]
I had a report this morning as well of this possibly looking at pending cash when only snap was checked, I am on phones so can’t look further into it right now.

**Comment by CDPotter** [comment]
Well the script was changed so you no longer have to pick programs (this threw me off too when I opened it.) so I'm guessing it checks all progs somehow (I'm still catching up from Mon/Tues)

**Comment by courtrightd** [comment]
So that’s maybe causing a problem when you approve SNAP but cash is still pending, it may not always even have an unapproved version of cash to look at.  I’ll try and look into it more later.

**Comment by CDPotter** [comment]
We also had a report that when DWP is pending the script errors out with this error. Seems like even though the script finds an unapproved version it is still doing the actions after it. 
![script error](https://cloud.githubusercontent.com/assets/7841989/12627753/3563cb08-c505-11e5-84cd-1721b19c89c9.png)

**Comment by C-Love** [comment]
Was anyone able to take a look at this? Any ideas? I was out yesterday and things are a bit hectic around here today. The looking for 'APPROVED' part of the code was not changed. I am wondering if there is some weird variable carry over, I think I would start blanking that variable out at the end of the loop. I only checked it out briefly this morning and couldn't see anything glaring. 

As soon as I get time, I will take a much closer look, but if anyone else sees it - jump in!

**Comment by CDPotter** [comment]
We just threw an older version in county customized for now. The issue we spotted was because the script was reading a date then trying to Cdate it. However if it finds an unapproved version (we saw it happen when someone approved initial SNAP but not initial CASH) it reads something that can't be Cdate'd and breaks. 

Personally I think it could use a bit more testing and I miss the functionality to pick if I want to autofill from cash or SNAP. I ran it on a case where I didn't need to approve MSA since there was no change but it still hunted down and grabbed $0.00 from the ELIG/MSA screen. Less thorough workers will miss this causing bad case notes. 

![2016-01-28 08_02_55-c__users_cdpotter_desktop_approved vbs - notepad](https://cloud.githubusercontent.com/assets/7841989/12646423/a0e325f0-c595-11e5-89ab-d7466dde6a0b.png)

**Comment by C-Love** [comment]
I think it is redundant to select the programs twice, once at the top and once where you pick the autofill. We could add logic to use those check marks to determine which programs are being case noted, if we like. However, the only time it should be in there is if the approval was on the same date and the only way that would happen is a denial and approval at the same time, in which case there should be a denial case note AND I don't think it would be confusing to have $0 amounts listed on a program that has a denial case note from the same day. 

I did make a quick change so that the user isn't alerted to approvals not being case noted for programs they did not check off. 

I found the problem, there is a missing 'Else'  in there. I will send it through. 

Thank you for the help with testing, that is what it is in the Maser branch for.

**Comment by CDPotter** [comment]
I'll send some screenshots.

**Comment by theVKC** [comment]
@CDPotter: please don't suggest that scripts in master "could use a bit more testing": this is why we have the master branch and why I've suggested to most agencies that they limit master branch access to select individuals. The master branch is not designed to be the only available branch to an entire agency.

**Comment by CDPotter** [comment]
My apologies @C-Love.

**Comment by C-Love** [comment]
Thanks @CDPotter  - It's all good.
