### ISSUE TITLE
TYMA TIKLer

### ISSUE THREAD

**Issue by CDPotter** [MN-Script-Team/DHS-MAXIS-Scripts#1754]
Ok bit of history on this one! I was approached by a worker to create a TYMA TIKLer that TIKLed/Case noted certain events. These events being:

TIKL to send 1st quarter report form month 3 day 20
TIKL to send 2nd quarter report form month 6 day 20 (also case note that 1st quarter form was sent)
TIKL for return of 2nd quarter report form month 7 day 21 (also case note that 2nd quarter form was sent)
TIKL to send 3rd quarter report form month 9 day 20
TIKL for return of 3rd quarter report form month 10 day 21 (also case note that 3rd quarter form was sent)

I created one script to do all of the TIKLs at once based on a start month/year (however it wouldn't case note as time went on that each form was sent.) The PCs here at Anoka did not agree with the procedure of TIKLing all at once. 

So I created a 2nd script that works similar to a dail scrubber. The first time it is run it will ask for the start month/year and TIKL for the 1st event. Then when the 1st event's TIKL shows up you run the script on that TIKL, it will read it and know the next step in the event list and perform those actions. 

In a small polling of agencies I've determined that there is a spread between these two methods. 
TIKL all at once: Ramsey, St Louis, Goodhue(but they were open to the idea of the "as you go" script)
TIKL as you go: Anoka, Carlton

What are everyone's thoughts on how to resolve this. They are both built currently as stand alone scripts so either one could be adopted to the state supported and the other could be used in county customized. 

My thoughts were:
1: We go with one or the other on the state powerpad (personally the "as you go" is a bit more powerful and avoids out of date TIKLs)
2: We work it into global variables and figure out how that will work behind the scenes.

**Comment by theVKC** [comment]
I have no say in this as I'm a SNAP person, but my vote would be that everyone does it the same, most efficient way (TIKL all at once). Lots of things leave TIKLs out unnecessarily long, and worrying about TIKLing too much "in case a case closes" is a slippery slope ("we shouldn't TIKL for 60 days in case the client doesn't stay open"). But, that's just my two cents.

Also, we can build a "show me all the TIKLs for the next 10 years" script if we want (but since DAIL/DAIL already has this functionality built in, it's arguably unnecessary, but it would make it easier).

**Comment by theVKC** [comment]
Now, can we get input from other @MN-Script-Team/county-agency-scriptwriters?

**Comment by Y-Lor-Y** [comment]
I’m part of the Ramsey County vote above noted by CDPotter.  I will say this.  In my opinion, but methods isn’t very different from one another.

One method you done all your TIKL’ing from the front end.

The other, you do them as you go or at the back end.

If I’m reading the DHS supported TYMA Guide powerpoint in Trainlink (at about slides #92?)  My take away from that was…to ensure there is a ‘tracking’ system in place.  Both methods above are in my opinion a tracking system.

I prefer the front end approach to this.  Also to note that this time around, TYMA should be a lot less – being it’s only for Parents/Caretaker with AA status mainly.

ONLY time these individuals may qualify are if they’ve never been assessed using the FIATED code 04 – for 2014 HC income standards (which is at 133%), and due to some changes in the income(s), caused them to be both over the 2013 and 2014 income standards.

Yang T. Lor | FCM Resource Trainer
Financial Assistance Services |  Ramsey County CHS
160 Kellogg Boulevard East, Saint Paul, MN  55101
P: 651-266-3621  |  Fax: 651-266-3705
E: yang.tou.lor@co.ramsey.mn.us
Schedule: M to Th, 7:45 AM to 6:00 PM
www.ramseycounty.us<http://www.ramseycounty.us>

The information included in this email message, including any attachments, is intended only for the person or organization to which it is addressed.  This email message may contain information that is privileged or confidential.  If you receive this email message and are not the intended recipient or responsible for delivering the message to the intended recipient, you may not use, disseminate, distribute, or copy the information included in this email and any attachments.  If you received this email by mistake, please reply by email and destroy all copies of this message and any attachments.  Thank you

**Comment by Farleight** [comment]
I'm also part of the aforementioned counties, so my opinion is known. I will add though, to your "most efficient way" comment, that with TYMA, people RARELY make it to the end of the year before there is a change that either makes them eligible under standard limits again, or closes them completely. That is why I believe all at once TIKLing would be the least efficient way to go... but that said, I'm good with either theory. Whatever the group decides is fine by me.

**Comment by CDPotter** [comment]
Just for transparency it has been decided here at Anoka that they will only support the "as you go" method. If it is decided that the state supported script is the one to TIKL all at once Anoka will use the "as you go" in our county customized. I should still be able to upload the "All at once" so this can stay assigned. (I am also willing to share the as you go with any agencies that are completely opposed to the "all at once" method.)

**Comment by corinne-stearns** [comment]
In Stearns we do this as we go vs. all up front.   Also, may not want to be setting for a complete year at this time - All MAGI cases are planned to be converted by 9/1 to MNSure anyway?

**Comment by Y-Lor-Y** [comment]
I believe I heard back in 2013 that by 2015 all HC would be on CURAM.  ☺

Yang T. Lor | FCM Resource Trainer
Financial Assistance Services |  Ramsey County CHS
160 Kellogg Boulevard East, Saint Paul, MN  55101
P: 651-266-3621  |  Fax: 651-266-3705
E: yang.tou.lor@co.ramsey.mn.us
Schedule: M to Th, 7:45 AM to 6:00 PM
www.ramseycounty.us<http://www.ramseycounty.us>

The information included in this email message, including any attachments, is intended only for the person or organization to which it is addressed.  This email message may contain information that is privileged or confidential.  If you receive this email message and are not the intended recipient or responsible for delivering the message to the intended recipient, you may not use, disseminate, distribute, or copy the information included in this email and any attachments.  If you received this email by mistake, please reply by email and destroy all copies of this message and any attachments.  Thank you

**Comment by theVKC** [comment]
We could certainly make it a global variable, which would be my vote if it's so evenly split. I'm working on the installer right now, so it's a good time to make such a change if we so choose. :)

**Comment by theVKC** [comment]
...or we could just let workers decide too. Thoughts?

**Comment by CDPotter** [comment]
Hmm... letting workers decide might be complicated if someone's case gets transferred to a worker who processes the other way. I'd vote global variable if we're gonna roll with both.

**Comment by courtrightd** [comment]
Global variable.

**Comment by theVKC** [comment]
I think we're decided... global variable, counties decide. @CDPotter: once your pull goes through, I'll add a global variable to the installer. If you can add a global variable to globvar, that'd be swell.

**Comment by CDPotter** [comment]
Ok, I'll get to work making it a dual version.

**Comment by CDPotter** [comment]
Also are we going with the Dual version only(meaning run the main script on the message), or the dual version + dail scrubber enhancement?

**Comment by theVKC** [comment]
I don't know. You tell me! What are you thinking with it? :)

**Comment by CDPotter** [comment]
It would probably make more sense to do the later as people are used to using the dail scrubber. If we told people to use the script like the dail scrubber we'd probably get questions to make the enhancement later anyways.

**Comment by theVKC** [comment]
So you'd be thinking the two scripts then? A DAIL scrubber enhancement to work with the TIKLs and the source script itself? (I like that)

**Comment by CDPotter** [comment]
Yup, so the source script will either TIKL "all at once" or just the first one based on county preference then the counties who do "as you go" can use the dail scrubber to work on the TIKLs.

**Comment by theVKC** [comment]
I think that makes sense. Counties who don't TIKL wouldn't ever need to worry about that extra DAIL scrubber script.

Can you make a separate issue for the DAIL scrubber script please?
