### ISSUE TITLE
BUG -- Multiple bugs with Approved Progs related to GA, MSA, and MFIP

### ISSUE THREAD

**Issue by RobertFewins-Kalb** [MN-Script-Team/DHS-MAXIS-Scripts#1771]
It's a matter of the wrong array position being case noted. I'm working on a fix.

**Comment by theVKC** [comment]
@C-Love, you might want to review this in case you're working locally at all.

**Comment by RobertFewins-Kalb** [comment]
I have tested the GA and MSA bits and they are working (the benefit month/year fields on ELIG/GASM are different than they are on other programs... 20,54 and 20,57 on GA, 20,56 and 20,59 for SNAP, MFIP, DWP and MSA...I have adjusted the coordinates). I have heard no complaints from family cash workers and I have no family cash programs to test it on, but I went through the code where the script reads the issuance for DWP and MFIP and it should be working. I'm going to submit a fix.

**Comment by RobertFewins-Kalb** [comment]
HALT

**Comment by RobertFewins-Kalb** [comment]
A bug was reported with MFIP. It appears the script is not accounting for the MFIP significant change determination page in ELIG/MFIP. I'm going to modify my pull to account for this as the writing coordinates are not the same on ELIG/MFSC as they are with ELIG/MFIP

**Comment by RobertFewins-Kalb** [comment]
OK.

**Comment by theVKC** [comment]
I think that second thing is a separate issue. Can you create a separate issue for it please @RobertFewins-Kalb?

@C-Love: I'm leaving the pull request out so that you can test it. Want to make sure we avoid any merge conflicts (also want your approval on this since this overhaul was your work).

**Comment by RobertFewins-Kalb** [comment]
I do not have time. This works.

**Comment by CDPotter** [comment]
It does appear to be working better as the version live in MASTER right now is writing the SNAP amount for MSA and GA.

**Comment by theVKC** [comment]
That's weird @CDPotter because I haven't pulled it. Any ideas?

**Comment by theVKC** [comment]
@RobertFewins-Kalb thanks for updating the title. In the future, I expect unrelated bugs to get separate issues. If they are related enough to be on one issue, I expect a comment explaining why. GitHub issues are used for tracking purposes beyond scriptwriters' convenience, and procedure must be maintained for the sake of that tracking. A second bug that "shows up" further down the comment chain of a single issue might be missed by individuals receiving notifications via email or RSS. Please follow this guideline in the future.

**Comment by theVKC** [comment]
@RobertFewins-Kalb alternatively, one can use the newer GitHub issue task list tracking, but I would prefer to relegate that to major ongoing projects, not unrelated issues.

**Comment by CDPotter** [comment]
I've used his fixes locally and it auto-filled properly, that's what I was referring to. 

I've run the one that was live 3 times. 

Once last week on a SNAP/MSA case where I didn't approve a new version of MSA as it wasn't needed. The new version of the script case noted that MSA was 0.00

Casey then submitted a fix. 

I then ran it Friday once on a GA reapplication case and it was again wrote 0.00

I ran it today on an initial MSA case and it again wrote 0.00

Robert found that the wrong portion of the array was being written to case notes (it was writing the SNAP portions on the cash lines) along with a few other hiccups. 

While he was in there an issue was reported to us, rather than splitting it up into bits he decided to tackle it as well to make a complete full script to make sure it was working as a whole (including this new one we found.)  I'd say the point of this pull is to get the script to working shape once again.

**Comment by theVKC** [comment]
@CDPotter that's totally cool for the pull request (1 pull request solving 2 issues), but for consistency we need unrelated issues on separate issue numbers. It's better for folks who rely on RSS or email notifications to know what's up so they can alert team members.

**Comment by C-Love** [comment]
Thank you for keeping a close eye on this @CDPotter  & @RobertFewins-Kalb.
