### ISSUE TITLE
UTILITIES - INFO: update worker signature getting ubound error

### ISSUE THREAD

**Issue by theVKC** [MN-Script-Team/DHS-MAXIS-Scripts#1839]
Not sure what's going on with it. For now, I'm going to revert to the old version. @RobertFewins-Kalb: if you have time and want to debug this, please feel free. Otherwise, let me know, and I'll just close this issue as I've reverted to the old code.

**Comment by RobertFewins-Kalb** [comment]
I wouldn't be able to look at it this week. Although, I'm thinking that adding the Updated Signature button to the menu threw off the buttonpressed count further down in the script (where the email buttons are). I am not 100% about that though, since I tested the email buttons and they all worked fine.

Either way, I think we should just leave the update signature button off the INFO script. Maybe leave the revert as is since update worker signature is already in the utilities main menu.

**Comment by theVKC** [comment]
Mine seemed to work OK on it's own, but failed when connected via GitHub. That's making me think you're right about the count.

I'll close the issue. We can always reopen it.
