### ISSUE TITLE
Bug NOTES 1503, unable to update HCMI

### ISSUE THREAD

**Issue by CDPotter** [MN-Script-Team/DHS-MAXIS-Scripts#1919]
The 1503 script doesn't PF9 or NN when editing a HCMI panel. Adding this functionality. 

(also changing where script checks for MAXIS after dialog)

**Comment by theVKC** [comment]
As this is a notes and not an ACTIONS, this might not be critical enough for RELEASE. The user can still take care of it manually and I'm guessing it's pretty clear the HCMI wasn't updated (so they won't exactly miss that it didn't happen, right)?|

Thoughts?

Critical criteria: https://github.com/MN-Script-Team/DHS-MAXIS-Scripts#critical-issues

**Comment by CDPotter** [comment]
Well it's impossible to use the checkbox to edit HCMI without this fix. It just does nothing. I don't know how important it is to add the DP and if you click the checkbox the end user would assume it did it and thus not check.

**Comment by theVKC** [comment]
I think since it's primarily for noting (it isn't an ACTIONS script) I wouldn't call it critical. So, I'll close the RELEASE version. The more pull requests I accept on RELEASE directly, the more merge conflicts I risk. The February release was challenging (1-2 hours instead of 10 minutes), so I'd like to minimize this risk in the future.

**Comment by CDPotter** [comment]
Sounds good, Anoka is on Master so it won't affect us.
