### ISSUE TITLE
CAF script - add HC form option

### ISSUE THREAD

**Issue by suzchik19** [MN-Script-Team/DHS-MAXIS-Scripts#2013]
Hello -
Please add the DHS 3727 (Certain Pops renewal) to the Drop-down list for HC recert documents.
Thanks,
Susie - Dakota County

**Comment by theVKC** [comment]
Hi Susie! GitHub isn't exactly a "request it and we do it" system. It's more of a discussion forum, and if there is interest from scriptwriters (and their agencies), we modify scripts with ideas posted here.

That having been said, any interest from scriptwriters in adding this?

**Comment by CDPotter** [comment]
I was looking at it cause I could have sworn certain pops was already on there and it is, but it's the Combined Annual Renewal for Certain pops (which has it's own script), the one is question is a certain pops application (rather than renewal) which could be used to renewal someone's HC. 

Should be a quick change, though I've never seen that HC Application form used for a HC renewal before most people seem to get the 3876 Combined Annual Renewal for Certain Pops form.

**Comment by theVKC** [comment]
Since this is a fillable dropdown field, my vote would be to not do it (because anyone can fill anything in). If it's a rare circumstance I think folks should just add it manually (otherwise why would we use a fillable field for anything?). Any thoughts from scriptwriters?

**Comment by CDPotter** [comment]
That would be Anoka's gut since it's an application form rather than a renewal form so it would be a rare occurrence where a person got that form instead of a renewal form.

**Comment by theVKC** [comment]
@suzchik19: I'm going to close this. Because it's a fillable field, and we already have the Combined AR script, I think this would be overly redundant (and possibly confusing since Combined AR isn't commonly used in this context). The CAF script is challenging to update because of it's size, and I'm hesitant to incorporate a lot more features into that field.

**Comment by suzchik19** [comment]
So where do the little people request changes or fixes?

**Comment by suzchik19** [comment]
Okay thanks for the info. I’ll pass it along -

Thanks,
Susie

**Comment by theVKC** [comment]
@suzchik19: this is where ideas are requested. But, requesting a change doesn't guarantee it takes place. If you had a scriptwriter, you could always ask them to do it (and if the enhancement was already completed, it'd merely be a conversation of merging the versions, not adding new code).

Please note that the county collaborators and myself have limited time to build enhancements, and we don't always take every suggestion. If an addition is not a priority for ourselves, it's unlikely to be added considering all of our other work. The only way to be sure to have a scriptwriter interested is to have a scriptwriter on staff in your agency who's willing to do the work. Other than that, it's up to counties/agencies with scriptwriters to decide what gets added and what doesn't.

**Comment by suzchik19** [comment]
Thanks for the info -

Are we still able to report problems with scripts on github?

Susie

**Comment by theVKC** [comment]
Yes, @suzchik19. You can report a bug, but first make sure it's happening with multiple users in your agency, on multiple case numbers and/or x1 numbers (depending on context). As we had with SIR, client data shouldn't be posted here.

Please read the project README for more info. https://github.com/MN-Script-Team/DHS-MAXIS-Scripts/blob/master/README.md
