### ISSUE TITLE
Bug Dail scrubber REVS scrubber verbiage/inquiry handling

### ISSUE THREAD

**Issue by CDPotter** [MN-Script-Team/DHS-MAXIS-Scripts#2098]
Notices two things today. 

One I accidentally ran it in inquiry and it got into an infinite loop trying to pf9 on case note. 

Two the verbiage on this seems contradictory to me. I had a client who didn't contact and didn't send in CAF so it seems according to the sentence send a nomi but according to "press no" statement click no?

![nomi](https://cloud.githubusercontent.com/assets/7841989/14431851/2c9da43c-ffcd-11e5-99e7-61eee05faf14.png)

**Comment by Farleight** [comment]
Yes. No, I would agree. That isn't not confusing.

**Comment by theVKC** [comment]
I'm confused by this.

* Issue 1: don't be in inquiry. :P Pretty sure the DAIL scrubber stuff navigates to case note differently because of folks' desires to go back to the DAIL message when it's done. If anything, something should check for inquiry earlier, but that might be hard to do. I'm open to suggestions.
* Issue 2: I'm open to updating this. Do you have better wordsmithing in mind?

**Comment by Farleight** [comment]
To be clear... Is there any updated info on this from what's in Poli/Temp? It suggests a MEMO (not a NOMI) for recerts, and lists this stipulation:

NOTE:  This SPEC/MEMO text should only be used for situations
where a FS Recertification is due, the county contacts
the client OR the client contacts the agency, schedule
an interview in person or by phone, the client misses 
the scheduled interview and either a CAF has been     
submitted to the agency or no CAF is submitted to the 
agency.                                               
                                                      
This SPEC/MEMO text is NOT to be used when the FS     
recipient never contacts the agency and no CAF is     
received.  When there is no request for further       
assistance the client will receive the proper closing 
notices from the MAXIS system.                        

If that is accurate, do we want to be creating NOMIs for these people at all?

**Comment by theVKC** [comment]
That's what this does, actually. At least, I'm pretty sure. We just call it a NOMI because it is a "Notice Of Missed Interview", same as the SPEC/LETR. I'm open to changing the name.

**Comment by CDPotter** [comment]
1: yes that was entirely my fault but any other user might not understand immediately what went wrong. Strangely enough it already has a start_a_blank_case_note in there.

2: My gut would say we send Nomi if we get CAF but they don't complete interview. So the change I would add would be "A NOMI is needed when a client has not completed interview but has turned in Recertification paperwork."

**Comment by Farleight** [comment]
I would say that is consistent with Temp then, Mr Pottehr (I'm hoping you imagine me pronouncing that like they do in Welcome Back, Kotter) As for the NOMI/MEMO issue, the "name" of the script is not either of those things, so I don't think a change is required there. Maybe just list it as either/or in the dialog.

**Comment by IlseFerris** [comment]
Ok I'll add my two cents...

The verbiage is not great (this is coming from the person who wrote it), and now looking at it, I don't think it's necessary. Since this DAIL message is created by the REVS scrubber (which sends out an appointment letter), it fulfills the criteria that the county has made contact with the client to schedule an interview. If they did not complete the interview at the time, then we send the NOMI. 

Also I think it should still be called the NOMI since that is what POLI TEMP calls it, even though we are sending a SPEC/MEMO instead of the SPEC/LETR. Here's the renewal part of the POLI TEMP reference, although @Farleight already referenced it earlier.)

POLI TEMP TE02.05.15- NOTICE OF MISSED INTERVIEW
"This SPEC/MEMO text should only be used for situations where a FS Recertification is due, the county contacts the client OR the client contacts the agency, schedules an interview in person or by phone, the client misses the scheduled interview and either a CAF has been submitted to the agency or no CAF is submitted to the agency.                                                
                                                       
This SPEC/MEMO text is NOT to be used when the FS recipient never contacts the agency and no CAF is received. When there is no request for further assistance the client will receive the proper closing  
notices from the MAXIS system."

**Comment by CDPotter** [comment]
So maybe change the question to:

A NOMI is not to be used when SNAP recipient never contacts agency and no renewal form is received. 

Then worker can click YES send, NO don't send CANCEL cancel

**Comment by theVKC** [comment]
I think if you ask that question, you should cite TE02.05.15.

Tagged it for May, calling it an enhancement. Do you want it, @CDPotter? If you can get it done sooner, let's take it.

**Comment by theVKC** [comment]
(or at least reference TE02.05.15)

**Comment by CDPotter** [comment]
I can do it this afternoon quickly enough.
