### ISSUE TITLE
BUG: LTC COLA Summary

### ISSUE THREAD

**Issue by CDPotter** [MN-Script-Team/DHS-MAXIS-Scripts#2276]
Looking at 01/16 still not 07/16. Submitting fix.

**Comment by theVKC** [comment]
Shouldn't this be either a selector or somehow determined by logic? We normally don't condone manual updating of a script as time goes on, save for policy standards.

I don't think we should keep updating this in this manner, I'd prefer to have a field to select the January or July COLA processing. Can you do that, @CDPotter?

At that point, this might be considered critical because LTC can't use the script as it currently exists. Care to weigh in on that @IlseFerris?

**Comment by IlseFerris** [comment]
Making this as hands free as possible would be the best option. This is critical if users can't use the script. I believe the COLA DAIL messages came out today.

**Comment by CDPotter** [comment]
Probably won't have time to build in that new feature today (tomorrow is flex and I'm out Wednesday morning, then Thurs/Fri is recert interviews.) If someone can get to it sooner by all means go for it. I was just submitting a temp fix.

**Comment by CDPotter** [comment]
Side question, script name is LTC - COLA SUMMARY 2016. Want me to remove the date?

**Comment by theVKC** [comment]
Please do!

**Comment by theVKC** [comment]
@CDPotter, @IlseFerris... I'm guessing the script as it's currently written isn't usable for the current COLA, right? Can we confirm that, then I'll mark it as critical?

@CDPotter, can you send this to RELEASE as well just to be safe?

**Comment by CDPotter** [comment]
Correct is it currently hard coded to look at ELIG/HC 01 16 only.

**Comment by IlseFerris** [comment]
Fact. This is critical.

**Comment by theVKC** [comment]
Reopening and marking as critical. Please pull into RELEASE if you haven't done so already @CDPotter. Thank you!

**Comment by theVKC** [comment]
Closed by #2295.
