### ISSUE TITLE
REPT MONT Bulk script

### ISSUE THREAD

**Issue by IlseFerris** [MN-Script-Team/DHS-MAXIS-Scripts#2278]
Hennepin County supervisor requested a REPT/MONT list be created. Pretty much the same thing as REPT/REVW, just for the MONT panel. 
I can take this unless anyone has a burning desire to take this issue.

**Comment by IlseFerris** [comment]
@theVKC go ahead and assign this one to me.

**Comment by C-Love** [comment]
@IlseFerris I am talking to one of our supervisors here and I want to clarify - would this be a report from MONT or MRSR? The difference being - when a HRF is completed on MONT it falls off of the report, but completed HRFs are still listed on MRSR. MONT is beneficial for workers because they can edit a case from that screen but does not seem as useful for generating a report.

**Comment by IlseFerris** [comment]
The supervisor that requested this wanted REPT/MONT, but it makes sense to have both then (just like REVW and REVS). I can certainly make a REPT/MRSR as well.

**Comment by C-Love** [comment]
Should I make another issue for you?

**Comment by IlseFerris** [comment]
Yes please :)
