### ISSUE TITLE
Closed Programs - Case/note script

### ISSUE THREAD

**Issue by bblomer** [MN-Script-Team/DHS-MAXIS-Scripts#2333]
Our workers have been using the Closed Program script when eSNAP has been approved for the initial month and is closing for the following month.  Currently, the case/note indicates that they have until the end of the month to turn in verifications.  This is not correct.  They only have 30 days from the date of application.  The client would need to reapply and turn in the missing verifications when they reapply.  Can the script be modified or would you recommend to not use it for eSNAP cases?  Thanks!

**Comment by IlseFerris** [comment]
I don't think we should dissuade user from using the script, but we could update it so that the case note informs the user that the client has 30 days. Also once the 30 days has passed, they would still have an additional 30 days to provide information needed for the original application without needing to reapply again. 

Any takers on this one? If not, I can take it for the July release.

**Comment by CDPotter** [comment]
We found some PI's related to this questions 10654 and 15920.

My summary of PIs:

client applies 6/5/16, case closes for no postponed verifs 7/1/16, verifs rec'd 7/17/16 client must reapply since verification were not received within 30 days of application

alternatively, client applies 6/20/16, their case can be reinstated for 08/16 as long as postponed verifications are provided prior to 7/31/16.

@ruthmaloney is this correct?

**Comment by ruthmaloney** [comment]
Yes, the PQ’s Charles listed both state that expedited is different from a regular application and how you handle is dependent on the date of application.

If an expedited application is received before the 15th of the month, the client has until the end of the month to submit verifications without needing a new app.

If the expedited application is received after the 15th of the month, the client has till the end of the second month to provide verifications, after that they need to reapply.

Ruth Maloney

**Comment by IlseFerris** [comment]
Thanks for the clarification @ruthmaloney! @CDPotter Would you have time before Friday to update this by any chance?

**Comment by CDPotter** [comment]
I should be able to this afternoon.

**Comment by IlseFerris** [comment]
Awesome, thank you! There is also an associate issue that I am about to create. There are HCPM and IAPM manual buttons, and those have now been retired. A new button is needed. Can you take that too? I'll add the new link.

**Comment by CDPotter** [comment]
So it should link to just EPM?

**Comment by IlseFerris** [comment]
Pretty much :)
I just created the issue #2334

**Comment by CDPotter** [comment]
@ruthmaloney just so I'm 100% certain. 

Appl date is ON or BEFORE the 15th of the month. The client gets to end of calendar month to turn in postponed verifs. (PQ says they get 30 days from application so that's where I'm getting confused.)
appl 6/3/16, last day to turn in verifs 6/30/16 or 7/3/16?

Appl date is after 15th of the month. The client gets to end of 2nd calendar month to turn in postponed verifs. 
appl 6/17/16 last day to turn in verifs 7/31/16

**Comment by ruthmaloney** [comment]
My bad, you are correct

Ruth Maloney

**Comment by CDPotter** [comment]
No worries! Just wanted to make sure I got everything right, thank you!

**Comment by theVKC** [comment]
If I'm not mistaken (and it's been a bit since I built it), I intended on folks using "denied progs" for this functionality. As a worker, I usually entered a short little case note (1-2 lines) about closing for expedited, and didn't use this script (which back then was combined with denied progs into "closed/denied progs").

With our current understanding and process of "closing" vs "denial", it does make sense to me that this be considered a "closure" of benefits, and "closed progs" should be amended to include this option. @CDPotter is on it and I'm thinking it'll be available Monday-after-next.
