### ISSUE TITLE
Call for input: Removal of the NOTES - REIN script

### ISSUE THREAD

**Issue by IlseFerris** [MN-Script-Team/DHS-MAXIS-Scripts#2342]
I've had a request from a Hennepin County supervisor to have this script removed. Users are using this script instead of applicable renewal scripts, and important information about the case are being left out. 
I know this seems like an extreme measure, but since the script does not auto-fill, or do any other action it's my vote as well. Thoughts?

**Comment by theVKC** [comment]
I disagree strongly. We should improve the script to be more clear. Not remove it based on confusion in a single county.

**Comment by RobertFewins-Kalb** [comment]
It gets some use in X102. My vote goes to improving it.

`err_msg` handling & more thorough data validation are needed

**Comment by CDPotter** [comment]
I'm looking at stats for it here and it has been used 16 times in last 30. Looking at the script I think we need to think about what it should do and if there's already a script for that. 

To me it looks like it's designed to be run when someone submits something that makes them eligible for REIN. Since we aren't supposed to enter information in MAXIS until the program can actually be APP'd I could see this being a good place holder to show a worker is processing a REIN but cannot update MAXIS because the REIN isn't complete. However in those situations I personally just run the relevant application script (because of autofill) or documents received, followed by an approved programs. So I too see potential I think we just need to build on it. @devonne01 this one looks like it was yours. Any thoughts on beefing this one up?

**Comment by theVKC** [comment]
I am going to close this issue. Removing scripts should be restricted to only the following circumstances:

1. A script is completely superseded by another, newer script.
2. A policy change has made the script completely unnecessary.

In all other instances, the work should be toward the improvement and augmentation of our scripts.

**Comment by theVKC** [comment]
If anyone has specific enhancements to make or suggest, please create separate issues for them.

**Comment by theVKC** [comment]
I've updated the README to codify this criteria.

https://github.com/MN-Script-Team/DHS-MAXIS-Scripts#when-to-remove-a-script-from-the-project
