### ISSUE TITLE
Closed and Denied Programs: send to WCOM as Approved now does

### ISSUE THREAD

**Issue by tdahl21** [MN-Script-Team/DHS-MAXIS-Scripts#2408]
Hey Everyone,

One of my coworkers mentioned having each script that deals with an action taken on a case to bring you to SPEC/WCOM.  This improvement was added to the Approved Programs script, but it would also help people remember to check SPEC/WCOM on Closed Program scripts and other scripts that deal with action being taken on a case.  Thank you for your help as always!

Tim D
Kanabec County

**Comment by theVKC** [comment]
This is a rather large request, and is unlikely to be implemented across the board. But, I would be happy to consider individual scripts if you have a list. It's hard to add it across dozens of scripts, but if you have a few we can certainly take it under advisement.

Anyone want to do this for closed programs?

**Comment by tdahl21** [comment]
Hey Veronica,

I'm thinking adding this function to the closed programs and denied programs scripts would be the best ones to add this to.  Thank you, Veronica!

**Comment by theVKC** [comment]
Good deal! I've added it to the list. We'll go over it at hackathon Monday: if anyone wants it they can have it! If nobody wants it by the following Monday (I'll give it a week), I'll mark it as a sleeper issue and close it- sleeper issues can be reopened if scriptwriters decide they want to do them later on.

**Comment by C-Love** [comment]
Since we've changed Approved Programs to do this, I am finding that it is not beneficial to me. I prefer the NOTES scripts to end on the Case Note they wrote. I prefer to be able to read through my case note once it is written and ending the script there allows me to do that. Additionally, my process is to add a WCOM before running Approved/Closed/Denied and I often use a script to do that anyway so being navigated there does not benefit my work process that much. SPEC/WCOM also tends to be picky about footer month and I find that for intake cases the navigation ends me in a footer month that does not actually hold a notice to which I can add a WCOM. 

So my vote is to not do this. I am also creating an issue requesting that the Approved Programs be changed back.

**Comment by CDPotter** [comment]
I also gotta agree with Casey. It's nice to be left on the case note to review it, and delete it if needed. More often than not I navigate straight back to case/note without even checking the WCOM since my mind is in make sure case/note is right mode.

For a compromise maybe we could have a message box stopping at the case/note encouraging people to review, then on OK navigate to WCOM to review that?

**Comment by theVKC** [comment]
I agree with the WCOM MsgBox. I've had plenty of feedback indicating that the general WCOM navigation is unpopular.

**Comment by theVKC** [comment]
I'll leave this open for a week to solicit comments. If anyone wants to try and convince me by Friday, I'll listen. Otherwise I will be closing this issue on Friday. See #2415.

**Comment by tdahl21** [comment]
Great feedback!  Thank you for your thoughts on it, the work making the change, and trying it out!

**Comment by IlseFerris** [comment]
I vote against navigating to SPEC/WCOM. Ending the script at CASE/NOTE in edit mode encourages users to add more notes and review the notes that were made.

**Comment by theVKC** [comment]
No problem @tdahl21! I'm glad we tried it: we learned a bit about how users prefer their scripts to end, and that's a good thing.
