### ISSUE TITLE
Request for New Hire and Paystubs received

### ISSUE THREAD

**Issue by ramonalisa1** [MN-Script-Team/DHS-MAXIS-Scripts#241]
Received a request to add something about checking for CEI Insurance when a New Hire and/or Paystubs received script is run.  Possibly just another check box as a reminder to send out CEI forms for new hires?  I would try to tackle this, but I am pretty swamped this month at the county.....

**Comment by ramonalisa1** [comment]
Sorry I have been off the radar for a while.  Trying to fit in Scripts and Supervisisio is getting tough.  Here is the policy from the HCPM.  We are to review to see if other insurance is cost effective at application, renwal or when a change is reported where CEI may be involved.  I know my workers forget to address then when checking New Hires and paystubs.  This may be pretty low on this list since is really is or HC and not SNAP.  

Chapter 15 - Third Party Liability (TPL)
 Effective:  September 1, 2012
 
15.10.05 - Cost Effective Health Care Coverage - MA
 Archive
 

Cost Effective Health Care Coverage - MA
Medical Assistance (MA) clients are required to maintain or enroll in other health care coverage if it is determined to be cost effective. Evaluate health care policies for MA clients for potential cost effectiveness at application, renewal, and any time a client reports access to other health care coverage. It is important to identify and maintain coverage primary to MA to save public funds.

**Comment by theVKC** [comment]
Admittedly, it’s been a while for me since I’ve done this. But, here’s how I remember the procedure (and please, correct me if you think I’m thinking it through incorrectly):

1. You get the new HIRE.
2. You send out the verif request and EV.
3. EV comes back, indicates Other Health Insurance (OHI) is available.
4. You update MAXIS for income info (basically all the other programs), then you send out proofs needed for TPL.

I think the logic of doing it at two separate times may have been based on the vast majority of clients NOT having access to OHI, and not wanting to bombard clients with additional paperwork. But, my caseload was mostly adults without dependents, and the jobs they acquired were NOT likely to have OHI. This may be different for families, etc.

In any case, what I’m thinking would be a simple solution would be to add a checkbox for “Sent OHI documentation?” and then case noting that if checked. That way, if folks send it at the same time as the EV, they have a place to show that. How does that sound?


Caution: This e-mail and attached documents, if any, may contain information that is protected by state or federal law. E-mail containing private or protected information should not be sent over a public (nonsecure) Internet unless it is encrypted pursuant to DHS standards. This e-mail should be forwarded only on a strictly need-to-know basis. If you are not the intended recipient, please: (1) notify the sender immediately, (2) do not forward the message, (3) do not print the message and (4) erase the message from your system.

**Comment by ramonalisa1** [comment]
That sounds just like what I am looking for.  Easy peasy.
