### ISSUE TITLE
Male or Female radio options (BabyBorn) for: NOTES - CHANGE REPORT and Baby Born

### ISSUE THREAD

**Issue by kennyasalee** [MN-Script-Team/DHS-MAXIS-Scripts#2450]
A request from Ramsey County casemanagement was submit to add, Male or Female field, (radio option) to have the case note indicate new born's gender. I can take on these updates for both scripts. Let me know.

**Comment by CDPotter** [comment]
Will you be able to get this done by Friday? It's gonna be a short window this month and freeze starts again end of day 8/12/16

**Comment by IlseFerris** [comment]
I also had a worker request a field to indicate the HH member # for the mother. Would you be willing to add this one as well while you're working on the script? I will create the issue if you are willing.

**Comment by kennyasalee** [comment]
You bet!

**Comment by IlseFerris** [comment]
Thanks @kennyasalee! I'll make the issue, and tag you in it as the one taking it.

**Comment by theVKC** [comment]
We should probably use a dropdown with a "select one..." option instead of a radiobutton. Depending on the system or process, a radiobutton might include a default (and you don't want to screw that up when it comes to gender). A dropdown with a "select one..." option can be programmed to ensure the user affirms a particular choice, without the presence of a default.

**Comment by CDPotter** [comment]
Agreed, Radiobuttons are often not a good option.

**Comment by kennyasalee** [comment]
sounds good will do
