### ISSUE TITLE
NOTES / HCAPP script ~ Possibility of including a drop down for indicating what type of HC app was submitted....

### ISSUE THREAD

**Issue by ALJ10** [MN-Script-Team/DHS-MAXIS-Scripts#2495]
A request by a financial worker and supervisor:
"Since we do not have HCAPPs anymore, I’m wondering if there could be a drop box to select which type of application form we get – 6696 or 3876."

Has there been any discussions on updating this? Or would the existing script logic be sufficient?

**Comment by CDPotter** [comment]
I believe at last discussion we came to the conclusion that HCAPP stands for Health Care Application, therefore just leaving it as HCAPP works to future proof things and prevents a huge dropdown list. To me I don't think it matters too much which kind of HC Application we receive? It's been a while since I've gotten a fresh HCAPP with everyone moving to METS.

That said I don't have much of a hand in HC side of things so if people are interested in adding this change someone could look at it!

**Comment by Farleight** [comment]
The 3876's are frequent. We've had 400ish of them in our 7-county region in the last month. Likewise, we get a lot of 6696's that need to enter MAXIS for whatever reason. They are quite different forms so there could be a benefit to having the distinction. Carlton would embrace the mandate. :-)

**Comment by IlseFerris** [comment]
Agreed, anything to make health care processing less convoluted is a good idea.

**Comment by CDPotter** [comment]
If somebody wants it feel free to tackle it!
