### ISSUE TITLE
CSES Scrubber Discussion

### ISSUE THREAD

**Issue by CDPotter** [MN-Script-Team/DHS-MAXIS-Scripts#2586]
Hello all, after the large discussion yesterday I wanted to gather everyone's thoughts and bring them to the work group which guided some of the decisions with the change to the CSES scrubber. Please post your concerns here or feel free to email me Charles.D.Potter@state.mn.us if you're rather not post. I want to make sure to get everyone opinions correct when I bring it to the group. (Next meeting 10/24/16)

I know this is one of the most popular scripts and I'd hate to see it scrapped due to controversy.

**Comment by C-Love** [comment]
There are a few things that really stuck out to me in terms of concerns and needs we have as county workers and scriptwriters. 

1. Clarification on PRISM. It seems that if the information from the DAILs is NOT always the correct amount for the budget then what value are the messages particularly for SNAP clients. 

2. Following that, if PRISM needs to be checked for every single  message, what is the exact process that needs to be followed to ensure we have the right amounts to look at for the budget. Then we can program the script to pull that information.

3. Shouldn't all workers that process DAILs then have access to PRISM?

4. It would be helpful to see the FNS response to defining the realm in terms of CS Income and SNAP and when we should take action.

5. Since the appearance of CS DAILs is dependent on a link being made between a MAXIS case and a PRISM case there is starting to be a disparity of action on certain clients. To explain this further, the only reason a CS DAIL appear on a MAXIS case is because that case was previously approved with a referral to child support (PRISM). That used to happen on nearly all cases as health care programs required that. However, starting a few years ago health care cases have been moving off of MAXIS and soon will be entirely off for MAGI (most families) cases. This means that the MAXIS case is no longer linking to PRISM due to HC eligibility. This means that more and more SNAP cases will never even have this link and CS DAILs will not appear on those cases. That referral still happens on family cash cases - MFIP/DWP. **This means that client who have been on cash previously are going to be more impacted by whatever CS DAIL process is created. This treats SNAP clients differently due to a previous eligibility for cash - which is a civil right violation. This seems to be increasingly troublesome and problematic.**

6. Something that invariably comes up in this discussion is the idea of 'Known to the Agency' much of the concern is that once the DAILs appear then the worker must take action because it is 'known to the agency'. This implies that non-confidential information held in CS cases is automatically available to MAXIS cases. If this were the case then a complete sharing of  information/documentation should be the standard (paystubs received by one are automatically available to the other). This situation is a partial sharing of some information that needs further detail. In this sense it is more like a New Hire match. (This person has this job - worker looks in MAXIS - the job is known nothing further is needed or the job is not known and the burden is placed on the client to provide this detail.) **If we could define 'Known to the Agency' particularly in how that applies to information on a PRISM case for a MAXIS worker (and the difference if the do or do not have access to log into PRISM) this would help agencies truly understand where their responsibility lies.**

7. What is the wording of our Six-Month Budgeting waiver (from which all of this controversy stems)?

I might come up with more but that's what I have for now.

**Comment by LaLarson** [comment]
What she said! 100% what @C-Love said!

**Comment by LaLarson** [comment]
I liked what @Farleight said too... That in a perfect world (as long as "known to the agency" applies to CSES DAILS, which should be one of the first discussions IMO), information would be pulled from wherever it needs to be pulled from to be accurate, and then put next to the amount budgeted. From there the worker could choose to stop, update it, and re-run the script.... OR, they could say they are okay with it, check some boxes regarding what they want in the case note, and be done with that particular case.

**Comment by CDPotter** [comment]
Ok my meeting is next Monday so I wanted to give a brief summary that I will be bringing to the group. (I'm bringing everyone's messages here and their emails since this issue was create in full as well)

-	Should these DAILS even exist and be processed for SNAP? Are we unfairly treating SNAP clients who have had their cases linked with PRISM at some point in the past as monthly reporters? (be it either HC or MFIP/DWP related)
-	Where exactly in PRISM can someone get the accurate information? Is it just one location that the script could pull data from?
-	Reasonable certainty, how far do we expect workers to go to get reasonably certainty that CSES income will continue? With so many messages generated each month contacting every client to determine reasonable certainty is not feasible. 
-	What does FNS have to say about within the realm in terms of CS Income and SNAP and when we should take action?
-	Do CSES messages actually fall under known to agency?
-	What does the wording of the 6 month budgeting waiver say about this situation?

Let me know if I've missed anything.

**Comment by CDPotter** [comment]
Response after discussion yesterday:

- **Should these DAILS even exist and be processed for SNAP? Are we unfairly treating SNAP clients who have had their cases linked with PRISM at some point in the past as monthly reporters? (be it either HC or MFIP/DWP related)** Yes these are known to agency and must be processed. It is not differential treatment because with or without the DAIL the information is known to the agency, must be shared, and acted upon. Also the fact that these DAILs are received monthly does NOT make the SNAP recipients monthly reporters. 
Where exactly in PRISM can someone get the accurate information? Is it just one location that the script could pull data from? The DAILS are accurate. The DAIL/CSES messages are accurate.  These messages are generated to inform workers of the child and spousal support disbursements made by the Child Support Payment Center. The DAIL/CSES messages do not include child care or medical support disbursements.  For SNAP unit members receiving a child care support disbursement, to obtain or confirm the child care support amount it may be necessary to view PRISM information or contact the county’s Child Support unit.   If you feel the messages are not correct that they submit a PF1

- **Reasonable certainty, how far do we expect workers to go to get reasonably certainty that CSES income will continue? With so many messages generated each month contacting every client to determine reasonable certainty is not feasible.** Look at the previous history of each case on a case by case situation,  and work with your Child Support (CS) unit to determine the history disbursement can be anticipated with reasonable certainity.  Due to the ongoing receipt of current child support income subsequent CSES DAIL messages will be received. The CSES DAIL messages may display varied amounts of current child support some may vary substantially, and others may vary slightly. If the current child support amounts displayed in the DAIL is expected to continue and is an amount not within the realm of past history/information used in projecting income for the current six month period then the worker must adjust the FS budget by updating the pop-up window on the STAT/UNEA panel to project a new monthly income amount for the remainder of the six-month period and approve the results. The worker must also document this in CASE/NOTE.
Contact should be made with the unit at application, recertification and when changes are reported IF the child support is outside of realm. 

-	**What does FNS have to say about within the realm in terms of CS Income and SNAP and when we should take action?** Within the realm is not defined by FNS.  DHS SNAP policy staff have used the information in the Combined Manual CM section 0022.03.01.03 Prospective Budgeting – Program Provisions to outline how to determine and  anticipate income including Child Support income and this CM information is based on the federal regulations.  
-	**Do CSES messages actually fall under known to agency?** Yes, See above. 
-	**What does the wording of the 6 month budgeting waiver say about this situation?** Six month budgeting is not a waiver it is a reporting option that MN selected.

**Comment by CDPotter** [comment]
These questions seemed to be answered by DHS and the script has evolved since this issue. I think it might be best to create new discussion in the future should we look back at this script.
