### ISSUE TITLE
Call for input: ABAWD help for workers 

### ISSUE THREAD

**Issue by IlseFerris** [MN-Script-Team/DHS-MAXIS-Scripts#2628]
We've got an ABAWD problem. With 3/36 ABAWD months, ABAWD exemptions, banked months, second set of ABAWD months, and banked months workers don't know which way is up, and cases are going to be all kinds of wrong. I want to get input on what we can build to help workers identify what is going on with their ABAWD cases. 

We've already got some great tools out there. ACTIONS - ABAWD FSET EXEMPTION CHECK, awesome. ACTIONS - ABAWD SCREENING TOOL, sweet.

Unfortunately, one of the roots of the problem is that workers are confused about the 36 month period: 
CM0011.24 Able-bodied adults
Able-Bodied Adults Without Dependents (ABAWDs) are applicants/recipients between the ages of 18 and 50. Unless they meet mandatory work provisions or an exemption listed below, they are eligible for SNAP for only 3 months in any 36 month period. The 36-month period begins the 1st full month the person receives SNAP. Once started, the 36 month period continues to run uninterrupted, even during times the person does not receive SNAP or is exempt from the time limit. You must explain these provisions to ABAWDs during the intake and eligibility determination process.

My initial thoughts are that since this time period can be different for each member, we start by identifying this period for each member. So @MN-Script-Team/dhs-scriptwriters, thoughts and comments please!

**Comment by CDPotter** [comment]
Probably a good idea, the rolling clock is rather complicated. Spelling out the period to look back over would be a great help for the screening tool (I thought we already programmed something in it to count months but maybe I'm mis-remembering)

Here is the verbiage from the 2013 USDA guide to ABAWDS ( @Farleight I have cited this thing so many times since you shared it with me.)  
"If an individual applies on January 1,
2014, the worker must look back to January 1,
2011 to measure any countable months during
that 3‐year period. The following month, February
1, 2014, the worker will look back to February 1,
2011 to measure the participant’s countable
months."

**Comment by Farleight** [comment]
It's going to be a tough gig. With all the various types of X's and M's and Y's and N's screwing up MAXIS' automated tracking, and no way to clarify what each month was other than manual case-note searching, I'm not sure how Scripty we can get with this one. Open to idea though. The tracking is going to be a nightmare. I typed this up for our county and the Region supervisors to pass along based on what we know. It's not a solution by any means, but if you'd like to disseminate info to the troops, it's a decent summary:

As MN began reissuing ABAWD months in 11/2013, we have now reached our first “36 month” threshold. Effective 11/2016, clients may be eligible for Initial ABAWD months again. There is still a good deal of unknown information in how we process these, and things will need to be looked at case by case until further instructions come out, but the state has clarified one major point for us.

MN has opted to use a rolling clock for ABAWD eligibility determination. This means that we will be looking back at the last 36 months for EACH month of eligibility that we are needing to determine. (Ex. If someone has used 11/13 and 12/13, but their final month was not used until 05/2016, then as of 11/16, they would be eligible for 1 initial month. As of 12/16, they would be eligible for another initial month. They would not be eligible for a third initial month until 05/2019)

The state is reviewing the possibility of switching to a Fixed clock (I have no idea how seriously), but for now we are using the above logic. I’ve attached the 2013 Federal ABAWD Guidelines PDF, accessible through FNS, which has a lot of good information for anyone who wishes to look deeper into this. (Pg 6 deals with the 36 month clock).

Things to watch out for when processing:

Additional months: When an ABAWD client has used their initial months, but later meets the FNS requirements (working 30 hours, et al), and subsequently loses those hours, they would then be eligible for a second 3 month period, which should run consecutively. If properly processed, this will show up with a different code in WREG tracking (Y or N), making it easier to tell the difference. However, this is not a guarantee. The additional months are also subject to their own 36 month rolling lookback period.

Other months on WREG Tracking: Whether for Banked, Earned, or  Additional months, WREG tracking may be covered with X’s and M’s. These codes interfere with MAXIS’ preprogrammed automated tracking of ABAWD eligibility. If a client has any months listed on tracking since the initial months were used, MAXIS will need to be FIAT’d for correct results. Details for this are highlighted in Poli Temp TE02.06.02 KNOWN PROBLEMS AFFECTING SNAP ELIG, on pg 8. Workers will need to be aware of what each tracked month was when processing these cases.

Things we don’t know:

The state has not given us information yet on how Earned months should be counted in a 36 month period. (Whether they count as part of the initial group, or are treated separately) Based on coding, it seems logical that they would be considered initial months, as the workers would have been manually deleting previous codes throughout the earning process. But this is not confirmed.

Banked months are not tied to the rolling calendar. Each state decides how they portion out banked months among clients, and the rules are subject to change in any given year. The state has not yet announced any plans for these to follow the same 36 month rolling lookback period (nor should we yet have cases in which the banked months are that old). They have not yet announced their plan for Banked Month allotment in 2017, so we will need to stay tuned for more information on that front.

Due to the complicated nature of ABAWD, you may find many issues arise that have not been mentioned here and that are unique to one case. Until further instructions come out Poli-Quest is your best source of information for issues you cannot resolve at the county level.

If you have any follow-up questions, feel free to ask. I may not have the answers, but I’ll pass along what I know.

**Comment by CDPotter** [comment]
Gonna sleeper this one until we get official word from DHS on the process.
