### ISSUE TITLE
HRF Enhancement

### ISSUE THREAD

**Issue by bblomer** [MN-Script-Team/DHS-MAXIS-Scripts#2647]
We have some clients that are open to MSA and turn in a monthly HRF.  Can a check box be added to the HRF script for the MSA program?

**Comment by CDPotter** [comment]
Is it someone turning in a HRF rather than a CAF or are there actually monthly MSA reporters?

**Comment by bblomer** [comment]
There are actually monthly MSA reporters who turn in household report forms….there is a CM reference to it if that helps…CM 7.03

There are not a lot of clients on MSA who are not SSI recipients but we have some…see CM 13.09 MSA basis of eligibility.

Thanks,

Bridget Blomer
Financial Assistance Supervisor
Scott County Health & Human Services
792 Canterbury Rd So
Shakopee, MN  55379
Phone: 952-496-8258
Fax: 952-496-8825


Privileged/Confidential information may be contained in this message.  If you are not the addressee indicated in this message (or responsible for delivery of the message to such person), please do not copy or deliver this message to anyone.  Rather, we ask that you: (1) please notify the sender by replying to this transmission and (2) please delete this message and any copy of it (in any form) without disclosing it.

**Comment by bblomer** [comment]
Just following up on this to see if MSA can be added as a program to the HRF case/note script.  
Thanks!
Bridget

**Comment by theVKC** [comment]
Hey Bridget and Charles! I built the HRF script way back when, so I'll weigh in a bit. 

If I'm remembering correctly (and it's been a while), we had thought that MSA, GRH, and family HRF recipients would want different scripts because some of the targeted questions were so different. We completed the family HRF and GRH HRF (and of course GRH HRF is now retired). MSA wasn't considered a high priority owing to the small amount of cases relative to the work involved.

But! We've clearly gone a different route with scripts such as CAF covering multiple program types.

My question would be: are there any fields on the current HRF script that would be confusing to MSA recipient cases? Stuff that should be added? That's the stuff that would impact whether-or-not I would have worked on it. I presume Charles would be in the same boat.

**Comment by CDPotter** [comment]
My gut would say this would be a simple add a checkbox change. The HRF script already has checkboxes for MFIP, SNAP, HC, and GA. Each of those options lead to the the same dialog. 

@bblomer is there anything that would be exclusive to MSA that isn't in the current HRF?

**Comment by bblomer** [comment]
Yes, is all we are requesting is that there be a checkbox to add MSA.  The script looks good beyond that.

Thanks,

Bridget Blomer
Financial Assistance Supervisor
Scott County Health & Human Services
792 Canterbury Rd So
Shakopee, MN  55379
Phone: 952-496-8258
Fax: 952-496-8825


Privileged/Confidential information may be contained in this message.  If you are not the addressee indicated in this message (or responsible for delivery of the message to such person), please do not copy or deliver this message to anyone.  Rather, we ask that you: (1) please notify the sender by replying to this transmission and (2) please delete this message and any copy of it (in any form) without disclosing it.
