### ISSUE TITLE
Application notes scripts enhancement: Adding reminder to check for reliacard accounts

### ISSUE THREAD

**Issue by CDPotter** [MN-Script-Team/DHS-MAXIS-Scripts#2672]
I'm getting word from MFIP people that workers are not entering or remembering to inquire about client's reliacards. They are seeing it come up as errors very often. 

His suggestion was a option on application scripts in which the worker will have to affirm yes/no that the person does not have a reliacard. 

Thoughts?

**Comment by CDPotter** [comment]
I had a few ssi/rsdi clients with direct express and bank accounts, so it does happen. So you're thinking making the CASH/ACCT field mandatory if UNEA is filled out? Veronica isn't a fan of adding stop points to the functions themselves so that option is out.

**Comment by IlseFerris** [comment]
It's possible for recipients to have an active Reliacard when UNEA has ended. 

This seems like information that should be added to the CAF and the 6054 forms. Otherwise it seems like we're getting into a 'worker interview script' if we are starting requiring workers to document every detail of the questions asked, and the applicants response.

**Comment by RoberT-1000** [comment]
No more WIFs, please.

**Comment by CDPotter** [comment]
Closing issue as this is more of a training issue/caf issue rather than a script solvable issue.
