### ISSUE TITLE
retire/rework banked month fiater/report

### ISSUE THREAD

**Issue by CDPotter** [MN-Script-Team/DHS-MAXIS-Scripts#2690]
With the banked month fiat process ending we probably can retire the ACTIONS-BANKED MONTH FIATER

However @senhorc suggested we pull out the WF1 referral portion since those still need to be manually generated. 

Thoughts? I was under the impressing we had a WF1 script but maybe that was localized to Anoka. 

The report can for sure be retired in the near future as starting with 4th Quarter (10/16) we aren't tracking Banked months that way.

**Comment by Farleight** [comment]
Paraphrased comment from similar discussion offline:

Don't retire the FIAT'r completely. It'll still be needed. MAXIS counts ALL months, so even the Y codes from Additional Months are still going to throw the count off... plus a lot of people code those wrong anyway, so even if it knew the difference, there will still be a need for FIATing. AND since Banked months really only became a thing this year and we're not deleting those codes, they won't expire for another 2-3 years anyway.

Perhaps better to remove Banked language from FIAT'r and rework it to meet ongoing generalized ABAWD FIATing needs.

(Credit to David for the productive part of this discussion... the whiny portions of "No, no, no. This simply will not do!," belong to me)

**Comment by IlseFerris** [comment]
Agreed, we should hang onto the FIATer, but we will need to make some general updates. I have an active issues to create a minor child FIATer, and much of the functionality is the same so merging into an ABAWD FIATer makes sense. Are there any other situations that need this level of fiating (income and deductions)?

Also the FIATER does not send WF1 information. The NOTICES - SNAP E & T LETTER has a manual referral option when needing to send referrals for banked months cases (and several other instances as well.)

**Comment by IlseFerris** [comment]
Also since I live a life full of banked months, I will take this.

**Comment by IlseFerris** [comment]
Can I get a consensus @MN-Script-Team/dhs-scriptwriters: Are they any other ABAWD situations that need to be fiated besides minor child in the home for non-parents? Is this is ready for retirement?

**Comment by theVKC** [comment]
As I work for PRISM, I am going to keep my opinions on this subject to myself.

**Comment by Farleight** [comment]
I'm assuming you mean besides that and the ones mentioned above, for WREG-Tracking confusion reasons... in which case, nothing sprang to mind that wouldn't involve ineligibility for various reasons where income would still need to deem to active members... but that's somewhat a separate beast.

And V, your opinions are still relevant. Have at it!

**Comment by IlseFerris** [comment]
Yes, besides the aforementioned ABAWD mess ;P

**Comment by IlseFerris** [comment]
Thanks for referencing this issue @courtrightd! So here's the hold up...
TE10.34.01 'ABAWD banked months': Instructions were updated in 11/16 to reflect ABAWD/FSET coding to be 30/13 (which is correct), but workers are still instructed to FIAT eligibility: 
> Send the case through background.  Ineligible results will be  
> determined due to the applicant/participant already using their 3 ABAWD months.  FIAT must be used > to obtain eligible SNAP results.        

Secondarily: TE02.06.02 'Known problems affecting SNAP elig': These instructions are incorrect since more than fiating the person test is needed. 
> ABAWDs who have used the initial 3 months of eligibility should again be eligible for the initial 3 month period of ABAWD eligibility after the 36 month period has ended, regardless of whether or not they used the 2nd 3-month period of ABAWD eligibility, see 0011.24 (Able-Bodied Adults Without Dependents).  Currently, MAXIS fails the ABAWD Person test if the ABAWD status field on WREG is coded with a 10-ABAWD Counted Month and there are more than 3 months with X, M, Y, or N entered on the ABAWD tracking record.  This does not follow SNAP policy.                                         
> Workaround:  FIAT the ABAWD Person test for the household member that MAXIS incorrectly failed.         

In order for DHS and counties to all be on the same page, I think that these TEMP references should be updated. Love to hear what everyone else thinks on this.

**Comment by CDPotter** [comment]
I would suggest PF11ing on the menu with the options (since you can't while in the topic) and detailing the discrepancy in the poli/temp and the actual practice. This should get it to the people who can re-write MAXIS or poli/temp I would think.

**Comment by IlseFerris** [comment]
Done and done

**Comment by CDPotter** [comment]
While policy is sorted out we have decided at Hackathon to temporarily disable this script.
