### ISSUE TITLE
CAF enhancement: Expedited documentation

### ISSUE THREAD

**Issue by CDPotter** [MN-Script-Team/DHS-MAXIS-Scripts#2749]
While at Hennepin today we received a suggestion that people would like to see an option to require workers to document expedited status and how they arrived at that expedited status. 

One suggestion was that we revise the "Reason Expedited wasn't processed (If applicable)" To be something more like Expedited Notes and this field would be required depending on if the expedited box was checked or not. The thought being that we want to document the client's expedited status and how we arrived at this conclusion AFTER the interview as this status can change since the expedited screening tool was run. 

Thoughts?

**Comment by CDPotter** [comment]
My gut is I would hate to see the original question go, however I do admit it's a bit confusingly worded. I'm wondering if maybe we don't turn the text field into a button which will have suggested topics of what to include in expedited notes (I'm thinking we could also expand this "help" button to all of the text fields at some point.)

**Comment by theVKC** [comment]
I came up with the wording, if I recall, in conjunction with an ME reviewer who is no longer with the agency. At the time, buttons + topics was problematic due to since-resolved max dialog limits. Personally, I'm in favor of that approach, as it could allow a much better method of communication than a straight text field.

**Comment by CDPotter** [comment]
If only we could have alt-text!

**Comment by C-Love** [comment]
We have a NOTES- Expedited Determination script that is meant to address this issue as a separate case note.

**Comment by theVKC** [comment]
Excellent point, @C-Love. I had imagined integration of the two at some point.

**Comment by CDPotter** [comment]
In discussions today it seems like we already have the tools for this and Hennepin's newer procedures will cover this deficiency.

**Comment by CDPotter** [comment]
Ok I have been asked by an ME reviewer to re-look at this issue:

It would be nice to have one neat case note where you can see a person's expedited status after their interview (most people don't run the expedited determination script in practice). A yes or no at minimum might be nice for their expedited status but ideally they would address why or why not. While the information could be gleaned from income/assets/shel/hest fields workers may enter 0s to prevent incorrect notices resulting in that information being pulled into the notes field and then the worker not noticing etc. 

Thoughts?

**Comment by C-Love** [comment]
We have maintained in this project the element of worker agency. (See the CSES Scrubber.) That has been a huge part of our project. We provide tools to assist worker BUT we do not dictate what they MUST do or which scripts they MUST run. We walk a thin line with mandatory fields, typically they are enforced when they are required for the script to function properly from that point on OR if they need to be mandatory to maintain the integrity of the intent of the script process. I actually have issue with having the notes on income field mandatory because we are stepping over the idea of worker agency.

NEXT we have been telling our workers that having HUGE case notes in which worker buries relevant case information deep within the text of the note does not best communicate the actions taken. We have encouraged the CAF note to be separate from Approved, which is separate from Denied. I see no reason to start changing here.

We have provided this tool and it works well, if workers are not utilizing it, that is up to individual counties to enforce on their workers. 

The answer is chainloading and until we have the functionality worked out, this does not make sense to me. This SAME issue is in Application Received and Expedited Screening. For most counties these processes take place at the same time and Application Received even reminds you to run Expedited Screening if SNAP was pended. Workers just have to be held accountable. Outside of workflows this is not a script writing issue, it is a training issue.

**Comment by IlseFerris** [comment]
For this issue, I don't think we need to look further than NOTES -EXPEDITED DETERMINATION. This meets all the concerns of the issue. Hennepin County instructs workers to use NOTES - EXPEDITED DETERMINATION to case note expedited criteria after an interview. I would be happy to share some of our training information and flow charts to support using the script in expedited processing. 

BULK - EXP SNAP REVIEW also looks for the case note created by NOTES - EXPEDTED DETERMINATION to assist counties in determining which cases meet EXP SNAP criteria.
