### ISSUE TITLE
MFIP/DWP Disqual Notes Script - Policy Question

### ISSUE THREAD

**Issue by khiestand** [MN-Script-Team/DHS-MAXIS-Scripts#2806]
I have a worker who found the "last day to cure sanction" date for DWP incorrect.  Clients have until the last day of the month to cure the disqual for DWP.  Worker states “The policy referenced is for MFIP only. DWP does not have the same rules. The client always has until the last of the month to cure a DWP disqual and may cure it into the next month if good cause exists. Sanctions do not exist with DWP so the consecutive sanction policy is not applicable.”

Does the script need to be split into 2 scripts???

**Comment by CDPotter** [comment]
@MN-Script-Team/maxis-scriptwriters Calling all DWP/MFIP experts!

**Comment by courtrightd** [comment]
Policy-wise, the script is definitely wrong with the last day to cure stuff for DWP.  I'm thinking instead of splitting the script, adding more options to the sanction status dropdown (separate DWP / MFIP statuses) that then effects what is noted / which fields are mandatory etc.  If no one has any objections, I volunteer as tribute.

**Comment by CDPotter** [comment]
Thanks @courtrightd !

**Comment by CDPotter** [comment]
@MN-Script-Team/maxis-scriptwriters Can I get some testing on this?

**Comment by courtrightd** [comment]
I can confirm that this has been tested on master and no reported issues.
