### ISSUE TITLE
Appointment letter including option for face-to-face interview: call for input

### ISSUE THREAD

**Issue by IlseFerris** [MN-Script-Team/DHS-MAXIS-Scripts#2823]
Several Hennepin County workers have asked for an option to add to the appointment letter that a client may need to have a face-to-face interview for DWP/MFIP. 

Suggested check box for dialog:  
"Check here if HH has applied for MFIP/DWP, and requires a face-to-face interview."

Suggested text for SPEC/MEMO:
"If you are applying for cash, a face-to-face interview is required. If you have been on cash assistance in the last 12 months, you may not need to be interviewed in the office. You may be able to have a phone interview."

Can I get some feedback @CDPotter and @ruthmaloney if this is possible?

**Comment by CDPotter** [comment]
So this is an exclusively Hennepin problem since they can't select phone vs office like the normal appointment letter script?

Maybe we could tackle it from another angle? What benefits does the Hennepin exclusive path have that the regular one does? By my memory it autofilled the date, and had the verbiage to have the client call instead of the worker. I feel like we could maybe have Hennepin use the normal version BUT we define some variables(IF county_code = 27) to what Hennepin needs for their processes.

**Comment by IlseFerris** [comment]
Yeah pretty much :)
I will address this with my PM's, and come to a consensus.

**Comment by IlseFerris** [comment]
This was a Hennepin County specific requested issue. This is no longer necessary due to a process change.
