### ISSUE TITLE
Bugs with returned mail WCOM

### ISSUE THREAD

**Issue by courtrightd** [MN-Script-Team/DHS-MAXIS-Scripts#2905]
Two issues, the dialog loop checks for worker sig, but there isn't a space for one in the dialog (it works if there is a saved worker sig on the user's computer). It also needs handling for multiple recipient memos (such as an AREP), which have an extra screen after PF9.

**Comment by kaleykobber** [comment]
We have noticed a bug with SPEC/WCOM, also - in the general sense - due to a MAXIS update, where the user can choose a recipient. This is causing issues with scripts accessing these notices. 

Ex. I came upon scenario such as: NOTES>Denied Programs, cant SPEC WCOM on noticed due to the following MAXIS update, an extra screen after you X Approval Notice, transmit, then PF9(EDIT). Ref: SPEC>WCOM>X>Transmit>PF9: You’ll get this pop up “Notice Recipient Selection”.  I had to manually stop the script.

**Comment by courtrightd** [comment]
I discovered after creating the issue that the MAXIS update is the problem as Kaley pointed out.  I'm starting a separate issue for the SPEC/WCOM issues, this can remain due to the worker sig problem.

**Comment by theVKC** [comment]
@courtrightd: any chance we can solve this issue at the same time as the other one?

**Comment by theVKC** [comment]
Repaired in #2907 and #2908.
