### ISSUE TITLE
New script: GA eligibility FIATER

### ISSUE THREAD

**Issue by IlseFerris** [MN-Script-Team/DHS-MAXIS-Scripts#2925]
Requested by Hennepin County worker. Script would be able to FIAT GA for prospective and retro GA budgets, and account for earned/unearned income of GA member and spouse (if applicable).

**Comment by Farleight** [comment]
This was the first script I ever worked on down in training. It was extremely rudimentary because I didn't know what I was doing, and GA was changing a lot at the time so I never really polished it, but yes, I'm all for this idea. I recall assets gave me some trouble, but with rule changes I don't know that that will be an issue anymore.

**Comment by devonne01** [comment]
I like this idea very much as well.

[Wright County, Minnesota]



Devonne Kent • Long Term Care Financial Worker •  (763) 682-7527

**Comment by C-Love** [comment]
Still a cool idea. However no code is done that we are aware of. 

Tagged for post freeze so it can be added to an issue list for the python repo.

**Comment by C-Love** [comment]
To be handled once conversion is over.
