### ISSUE TITLE
New script: NOTES - ABAWD TRACKING RECORD

### ISSUE THREAD

**Issue by IlseFerris** [MN-Script-Team/DHS-MAXIS-Scripts#2958]
Case note template that allows users to case note the happenings of the ABAWD tracking record. 

ABAWD cases reflecting counted months for more than the current 36-month look back period, second set issues/coding, banked months being counted or not counted on the ABAWD tracking record based on what month banked months applied, and not being able to rely on PEPR messages instructing SNAP closures are huge issues we are seeing here. In order to capture a point-in-time picture of the ABAWD tracking record, we've developed this script. This is especially helpful to case note ABAWD statues after checking for exemptions and/or updating the ABAWD tracking record. 

![image](https://user-images.githubusercontent.com/10836829/28544227-17dea9c4-7088-11e7-8060-59f54e16e753.png)

This is ready, and being used at Hennepin County. Will add to project once freeze is lifted. Will send code to any county in the meantime who would like to run it locally.

**Comment by Farleight** [comment]
I have a similar thing that I manually enter every month... I've thought about Scripting it, but haven't had the time... I actually start mine out with the "anticipated" usage of the following month, so that if there is a change in the meantime, I know exactly what I'm looking at. That has proven useful. Looks something like this:

ABAWD Tracker - Anticipated 08/17 use: Initial Months
.................                                    
Initial Months used: 02/16, 03/16,              
Additional Months used: None                         
Banked Months used: 08/16, 09/16, 10/16              
Additional Banked Months used: 11/16, 12/16, 01/17

**Comment by C-Love** [comment]
@IlseFerris - can we put this in the collaborative branch as well. Then we can have to code available for post freeze.

**Comment by IlseFerris** [comment]
https://github.com/MN-Script-Team/DHS-MAXIS-Scripts/tree/scriptwriter_collaborative/notes

**Comment by C-Love** [comment]
To be handled once conversion is over.
