### ISSUE TITLE
NOTES - Expedited Screening: Utilities Standards have changed eff 102017

### ISSUE THREAD

**Issue by C-Love** [MN-Script-Team/DHS-MAXIS-Scripts#2968]
I know that NOTES - EXPEDITED SCREENING needs to be updated.

Any others needed?

This is urgent - we use this script one EVERY new SNAP request.

**Comment by CDPotter** [comment]
I remember there being references in FUNCLIB as well.

**Comment by C-Love** [comment]
I did a search for the amounts in the DHS repo and FuncLib and I don't think we have these amounts hard coded in any other script.

**Comment by IlseFerris** [comment]
I looked yesterday too. they are not called in any current scripts. 
Sponsor income has some old income standards that also changed for 10-17 if you're updating scripts locally.

**Comment by C-Love** [comment]
I think those are the only scripts we have identified with this issue at this time. I will update status to testing for now. Unless anyone finds any more.

**Comment by theVKC** [comment]
My apologies for the delay, folks. I was unavailable when this issue went down due to an unforeseen absence, and DHS had nobody to back me up. I've (just today) been cleared by my sup to tackle some MAXIS bugs, so that we can clean things up before migrating functions over to a post-Windows-10 world. This means I'll be monitoring things in-the-meantime here.

Sponsor income issue is being tracked separately: #2944.

I can see that @C-Love and @IlseFerris pulled in commits for this but for some reason Casey's pull request (#2968) had some kind of whitespace issue which created problems in pulling in the changes. In order to process this quickly I'm taking the HEST amounts and dumping them in myself, using the old date-based logic (but this time with *2017* instead of *2016*).

**Comment by theVKC** [comment]
I've pulled this in. Testers.... go!!

**Comment by C-Love** [comment]
I have notified my testers that we need feedback on this ASAP. Will update when they actually start work (early shift is awesome because no one bothers me for a whole hour).

**Comment by IlseFerris** [comment]
@MN-Script-Team/dhs-scriptwriters so that we can get this committed all users, can someone test this script? Thank you!

**Comment by theVKC** [comment]
@C-Love, can you confirm this is resolved?

**Comment by C-Love** [comment]
Yes, I can confirm that the utility standards are now correct! 
Issue is resolved.
