### ISSUE TITLE
Enhancement to appt letr and notes

### ISSUE THREAD

**Issue by x158215** [MN-Script-Team/DHS-MAXIS-Scripts#2984]
If it is suppose to be known how we received the application, my suggestion would be to add a spot on notes, and appt letter in scripts how the caf/recert was received.

**Comment by C-Love** [comment]
There is a script NOTES - Application Received that is used for this purpose when pending new requests. Otherwise the NOTES - CAF script also addresses this issue. 

Sometimes when scheduling an appointment we have not yet received a CAF, so I don't know if it best goes in this script. Though if other counties have a different process, I would be interested to hear it and know where it would fit.

**Comment by C-Love** [comment]
For documenting where a CAF was received from, the NOTES - CAF script has a place for that, which will work for both re certifications and new applications.

**Comment by theVKC** [comment]
@C-Love, do you want to keep this issue open for now?

**Comment by x158215** [comment]
Our case aid keeps asking these questions, I am not sure what exactly she is looking for, maybe you can tell me if there is something that I am missing that she is requesting be done.
Thanks Veronica for all your help.

**Comment by theVKC** [comment]
No problem! We always want to capture ideas and see what scriptwriters in the counties think! :)

**Comment by C-Love** [comment]
I would advise against updating the Appointment Letter script with this functionality because that script is not meant for processing an application. Both the NOTES - Application Received and NOTES - CAF are intended to process application and have the policy correct area to indicate where the application came from. 

However, if there are other views on this, other counties might have a different process. I would be interested to know what concern is being addressed with this request.

**Comment by x158215** [comment]
Question: The appointment notice script does not ask how the caf/recert was received.  Could this be added to it?
My thoughts: This is our case aid that enters all CAF’s and schedules them for an interview, so I guess what she is asking on this is, can you add to the appointment letr script maybe right under App type: how the appl was received? This would solve the issue of using more than 1 script/case note for new appl’s and recerts.

Question: The “application received” script does ask for it (how was the appl received), but this doesn’t help with recertifications.  Which are different than applications.

My thoughts: The CAF-NOTE is for actual processing of the CAF, she is not processing, she is either assigning to a worker new CAF’s or she is scheduling appt’s for New CAF’s and for recertification’s, so she would not use the CAF case note script as she is not processing anything, she is only pending and assigning.

Does this make sense?
I guess the more I look at it, the more it makes sense to me.
We are required to case note how the appl was received for every app that comes in even if it is for recertification. Let me know your thoughts.
Thanks

**Comment by C-Love** [comment]
I see where you are coming from here. I can see the benefit. I will say the 'App Type' field on the Appointment Letter script is a bit of a misnomer. It doesn't really define the type of application - just the process in which the case is in, if that makes sense. 

The reason we have encouraged using Application Received (and also using 2 different scripts) is that Application Received gives a number of other details that are important and required when case noting an application, such as Confirmation Number if it is an applymn and the time. It also details who the application will be processed by AND what programs are being requested. If attempting to best follow policy on this, that is the script with the most complete policy information in the note. 

This is a problem I think many counties are facing, there are a series of scripts that are often run in succession particularly at receipt of an application, often including Application Received, Expedited Screening, and Appointment Letter. I would more be in favor of adjusting Application Received to better handle applications coming in that do not require an intake process.

**Comment by x158215** [comment]
Thank you Casey that does explain it much better and if you can solve the issue of using 2 or 3 scripts and save the case aides and intake workers that handle these it could save counties time and money.
I appreciate all the work you do for the scripts.

**Comment by theVKC** [comment]
Would this be something that would be resolved by our ongoing Pythonic conversion ideas, @C-Love? That involves daisy-chaining scripts together in new ways... letting many scripts effectively run like one? Thoughts? Perhaps this issue could be closed because Python will show us better tools to manage this sort of thing?

**Comment by C-Love** [comment]
Yes - I think this is a part of the workflows/daisy-chain process that will be possible with Python. I know that @MelissaFox-Stearns is interesting in this kind of workflow as well so do we have a tag for issues to be handled with conversion?

**Comment by theVKC** [comment]
I like it, @C-Love. Can you make tags?

**Comment by C-Love** [comment]
Yes - I will make tags!

**Comment by C-Love** [comment]
workflows once conversion is done
