### ISSUE TITLE
Foster care case note

### ISSUE THREAD

**Issue by theVKC** [MN-Script-Team/DHS-MAXIS-Scripts#342]
I'm not going to be able to work on this one since it's pretty far outside my SNAP mandate. But, if anyone is interested, here it is. It was originally requested by X105629. That user provided a template, which I can't upload here since it's a PDF (but I would be happy to provide to a potential scriptwriter). Seems logical and easy, I just don't have time at the moment to work too much on non SNAP scripts. 

There's a real chance for someone to be an intercounty hero, here. :)

**Comment by theVKC** [comment]
@LaLarson has graciously volunteered to take this on. Yay!

**Comment by IlseFerris** [comment]
@LaLarson did you get anywhere on this one?  We can reassign it if not, if so, we want credit where credit is due :)

**Comment by LaLarson** [comment]
You’re awesome… We assigned it as a good future project for me, but I have not touched it. Feel free to reassign if you need it done sooner rather than later! ☺

Laura Larson
IMU – Family Unit

Goodhue County HHS
426 West Avenue
Red Wing, MN 55066

Phone: 651-385-3200
Fax Numbers:

  *   Child Support Fax: 651-267-4880
  *   Income Maintenance Fax: 651-267-4879
  *   Social Services Fax: 651-267-4877

Email: laura.larson@co.goodhue.mn.us<mailto:laura.larson@co.goodhue.mn.us>



HHS Temporary Relocation Update

Effective Tuesday, February 17, 2015 Goodhue County HHS staff & services from the Citizen’s Building, 426 West Avenue, Red Wing, MN 55066 will be relocated to the old St. Joseph School, 469 – 12th Street, Red Wing, MN 55066.

The following divisions will be relocated - Social Services, Income Maintenance, Child Support and IT / HHS Finance.
The Public Health Division will remain at the Government Center & Colvill School locations.

This is a temporary relocation until the Citizen’s Building renovations / addition have been completed.  There is no change to phone numbers, mailing address or emails. Thank you.

Map: From Citizen’s Building to St. Joseph School<http://mapq.st/1D30asB>


NOTICE: This e-mail and any files transmitted with it are intended only for the use and viewing of the individual or entity to which they are addressed. If you are not the intended recipient, please immediately notify the sender of the transmission error and then promptly delete this message from your computer system. Please be advised that e-mail correspondence to and from Goodhue County may be public data subject to the Minnesota Data Practices Act and may be disclosed to third parties.

**Comment by theVKC** [comment]
Hi @LaLarson! 

I hear you're moving to adult programs. Would you like to remove this issue from your to-do list? If nobody takes it in a week or two, I'll close it.

**Comment by theVKC** [comment]
@LaLarson: any chance we can set up a time to work on this script/any others that might have come up?

**Comment by theVKC** [comment]
Marking this as help wanted. If nobody wants it by hackathon Monday, I'll close it.
