### ISSUE TITLE
Chain load a list of supervisors into an array using fancy new functions from over in CS land

### ISSUE THREAD

**Issue by theVKC** [MN-Script-Team/DHS-MAXIS-Scripts#344]
In my PRISM scripts (that I'm working on as an Anoka County employee, not a DHS employee) I made up this cool function, which you can review here: https://github.com/Anoka-Script-Team/Anoka-PRISM-Scripts/commit/e6ee7d715c9db10d9a5a4eea914f9bbfcb5cbbce

What if... we used that function, combined with issue #180 (program it to pull supervisors), to create a dropdown list on various BULK scripts for "select a supervisor to run their workers' lists". It would first scan REPT/USER for active users, then return (in a dimension of an array, because computers) a list of supervisors (and all of the attached workers because computers). That way, a supervisor can just pick their own name from a dropdown and instantly run reports for all of their staff... could be fun, eh?

Any takers? My spidey-sense is telling me that @RobertFewins-Kalb or @lpshanley might be interested. If nobody wants it, I will inevitably do this next month.

**Comment by RobertFewins-Kalb** [comment]
OMG -- related idea

What if the report generating scripts had an additional function that knows when the user is a supervisor (could add their x number to the global variables) and added a checkbox giving the supervisors the option of running the report generator for only their unit (rather than one worker at a time or for the entire agency)

Example:
 IF user_id_for_validation = <supervisor id> THEN supervisor = True
IF supervisor = True THEN
  CheckBox, ##, ##, ##, ##, "Check here to run this report for only your unit.", unit_check
END IF

In REPT/USER -- PF5 until List Sorted By = "SUPR"
Pull users

**Comment by theVKC** [comment]
I think my idea automates that, doesn't it? Instead of needing a global variable, it would dynamically check REPT/USER for all active users, and return a list of supervisors based on that logic... Think of how often a new supervisor is promoted/retired/etc. in the counties... I wouldn't want counties to have to reinstall scripts every time. Dynamic = very yes

**Comment by RobertFewins-Kalb** [comment]
That pretty much is the same...I just got all excited because (a) that = awesome, and (2) the training region is not allowing me to test the page 4 fix in the functions library (painfully slow).

Going through REPT/USER, it doesn't look like there's anything to indicate automatically who the supervisors are.
@CDPotter and I were wondering why we cannot get a list of supervisors from somewhere...data warehouse, for example. When you select a user in REPT/USER, you get this...

![image](https://cloud.githubusercontent.com/assets/7842016/5841020/43316b84-a15f-11e4-9c2c-34f83c657dd1.png)

That variable populating SUPR ID has to be stored somewhere...

**Comment by theVKC** [comment]
Data Warehouse isn't such a good idea, because computers.

I was planning on using the above SUPR ID. It's reasonably stable. Does that not constitute "automatic indication of supervisor"?

**Comment by theVKC** [comment]
Removed due to lack of interest/time/necessity. Will re-open if this becomes urgent.
