### ISSUE TITLE
CAF (NOTES #-G) footer month default to month viewing

### ISSUE THREAD

**Issue by ALJ10** [MN-Script-Team/DHS-MAXIS-Scripts#368]

**Comment by ALJ10** [comment]
I accidentally submitted this without an explanation. Oops! Anyways, workers in Crow Wing County are wondering if it's possible to have the CAF script default to the footer month they are viewing instead of having it default to the next month.

**Comment by ALJ10** [comment]
Afterthought: Either have it set to the month they are viewing or the current footer month. Hope that makes sense!

**Comment by theVKC** [comment]
It does. And this is actually the design, it's a known bug that it doesn't do it. However, even though it's known, I never added it to GitHub for some reason! Anyway, now it's there. :)

**Comment by lpshanley** [comment]
Im going to start working on this one!

**Comment by lpshanley** [comment]
Done and commited

**Comment by theVKC** [comment]
I think I see what's going on here... you didn't do this on a separate branch. When you work on two separate script ideas (like AGENCY CUSTOMIZED and CAF), you need to make two branches from master, one for each change. That way, if something ever goes wrong, I can revert the one without affecting the other. Does that make sense?

Here's how I think you solve this dillema:

1. Copy your changed code for both scripts. Save it somewhere you'll remember it.
2. Revert all commits. If that doesn't work, delete your fork entirely.
3. Pull request MN-Script-Team's main repo back into yours.
4. Create two branches, one for AGENCY-CUSTOMIZED and another for CAF.
5. Copy each script change you made (and copied in step one) back into its respective branch.
6. Pull request each branch.
7. When I accept each branch, go ahead and delete them, but only after I accept them.

I know it might seem goofy, but I'd never want to inadvertently introduce a bug by reverting some CAF commit in six months which somehow destroys AGENCY CUSTOMIZED. Does that make sense? It's about preserving the commits that relate to each other inside branches which can be easily reverted if anything goes goofy.

Otherwise, your changes look solid. And, they are VERY appreciated.

**Comment by lpshanley** [comment]
Now its done AND in its own repo!!!

**Comment by ALJ10** [comment]
Now that this has been fixed, do I need to run the config tool again? We are a beta county so I was thinking our scripts would automatically update. But when I went to use the CAF (just to test), it still shows next month as the footer month.

Let me know when you get a chance. Pls & ty!

**Comment by theVKC** [comment]
Actually, I haven’t pushed it out yet. All I’ve done is bring it into our working branch (the ones the scriptwriters use). Assuming that works well, I’m hoping for a beta release in the coming days.


Caution: This e-mail and attached documents, if any, may contain information that is protected by state or federal law. E-mail containing private or protected information should not be sent over a public (nonsecure) Internet unless it is encrypted pursuant to DHS standards. This e-mail should be forwarded only on a strictly need-to-know basis. If you are not the intended recipient, please: (1) notify the sender immediately, (2) do not forward the message, (3) do not print the message and (4) erase the message from your system.

**Comment by ALJ10** [comment]
Sounds good! Just wanted to make sure I wasn’t missing a step.

Thank you for letting me know! ☺
