### ISSUE TITLE
CAF Script enhancement for Certain Populations Application/Renewal

### ISSUE THREAD

**Issue by jasont35** [MN-Script-Team/DHS-MAXIS-Scripts#446]
Could the CAF script be modified to include the DHS-3876 (MHCP Application for Certain Populations) and the DHS-3727 (Combined Annual Renewal for Certain Populations) as a selection for Health Care document received. Also, clients who are renewing SNAP and/or HC that fall into the Certain Populations category receive the DHS-3727 as a renewal form. Is there a way to change the CAF script to show that the DHS-3727 was received instead of the CAF or should this be a new script?

**Comment by CDPotter** [comment]
The Combined AR (combined annual renewal) script is for 3727, and I've personally just been using the HCAPP script for 3876. 

As for adding it to the dropdown box for the CAF I've had it requested a few times at our county but we decided against pursuing it since the dropdown box is editable and workers could specify any other form rec'd.

**Comment by jasont35** [comment]
@CDPotter Thank you for the information. I relayed the information to the worker asking about this and they said that will work.
