### ISSUE TITLE
Enhancement Request for Actions - Transfer Case (ICT)

### ISSUE THREAD

**Issue by suzchik19** [MN-Script-Team/DHS-MAXIS-Scripts#555]
Request to add to the transfer case script for Inter-county transfer cases. 
- Add Inter-county transfer to transfer type selection
- Check if there is an active child care worker and offer option to change worker number at that point
- Check the County of financial responsibility dates and list in a message box
- Option for TIKLs - 
1. notification for worker receiving case: 
SEND OUT GAIN SETTLEMENT LETTER, SHELTER & CHANGE REPORT FORMS
2. 10-day follow up
SHELTER AND CHANGE REPORT FORMS SHOULD BE BACK TO PROCESS
CLOSE BENEFITS IF NOT RECEIVED

**Comment by CDPotter** [comment]
Maybe I'm misunderstanding the request but

- The script does already have a inter-county transfer function. When you run the script you check the radio button next to "Within the county/agency"
-Could you elaborate more on this? I'm not familiar with this process.
-The script does have sections to edit financial responsibility. it also allows uses to navigate to spec/xfer to see what is currently on there and gives users a chance to check the updated spec/xfer screen after they click ok on the script. 
-For tikls I don't know that we would need it since if you select that you sent a change report form an info message populates on the dail stating "CHANGE REPORT FORM SENT ON 10/21/14   DUE BACK ON 10/31/14" (taken from a training case dail)
-The notification for the worker would be to check the case note created by the script.

**Comment by suzchik19** [comment]
Hi -

I’m talking about an incoming transfer case. The w/in county transfer only has the following, and there are no check boxes other than program. There is no TIKL created.

[cid:image001.png@01D072C6.FCA1AF10]

**Comment by CDPotter** [comment]
Ah ok that makes sense!

I'm thinking we add a edit box for "Verifs requested" so workers can write what verification they requested, then a check box to tikl out for 10 days "Have requested verifications been returned? If not take appropriate action", and changing the dropdown menu to be an editable combo box to allow for more transfer to options other than adult/family.

**Comment by suzchik19** [comment]
Yes - that sounds great! Can you work the Child Care info in, too? This is nice to have since it helps to identify where a cash case should go.

**Comment by CDPotter** [comment]
I'm not really sure what you mean by child care info. I've only worked in the Adult Unit. Could you elaborate more on the process in detail?

**Comment by suzchik19** [comment]
Yes -

I am attaching a text copy of the Dakota Cty ICT script. I think it’s in the third section… Dialog for if CC active. Also in the case note section, pg 3.

The script looks to see whether there is a child care worker in MAXIS. Then it states who the CC worker is and asks the user if they want to change who they are transferring the case to. If child care is active that is also included in the Case Note title. EG. MFIP Gain Settlement Received. **CC Active**

This notifies the MAXIS worker of a separate case in MEC2 that needs to be transferred as well on MFIP/DWP cases.

Thanks,
Susie

**Comment by CDPotter** [comment]
Oh you guys already build something to do it? Would you want to try your hand to incorporate it into the active script? (side note I don't think the posting here on github allows for attachments.)

**Comment by suzchik19** [comment]
I do not know how to get it into an active script… yesterday I sent one to Veronica’s state email. Can I do that?

**Comment by CDPotter** [comment]
We prefer to use the push/pull methods in github for editing code. @theVKC would probably be able to get you the documentation or walk you through it.

**Comment by theVKC** [comment]
@suzchik19, Charles is referring to the document in SIR under the "Scriptwriter Resources" folder of the document library called something like "GitHub Collaboration Instructions". This document contains instructions for the proper way to share scripts your county has written. We try really hard not to email files because they can be filtered out by firewalls, and it puts additional work on your statewide coordinator to act as middle-woman. ;)
