### ISSUE TITLE
New Job reported / dail new hire message

### ISSUE THREAD

**Issue by CDPotter** [MN-Script-Team/DHS-MAXIS-Scripts#557]
I had a request from a worker to ask about an enhancement to these two scripts that would update the SNAP PIC and HC pic(in month +1) to be budgeting 0 in both cases. Before I dove in I just wanted to make sure that it was a state supported practice to put a 0 in a jobs panel SNAP and HC PIC until the job is verified. If this is good to go please assign this to me and I can get crack on it.

**Comment by CDPotter** [comment]
Ran into a few issues while pondering about this one(new jobs reported script first):

1. sometimes when you enter a panel into maxis it does not get carried over to the next month meaning if a new jobs panel was created in 04 and you told the script to update the 05 pic it wouldn't find the jobs panel and possibly edit another jobs panel.

2. My first gut solution was to emread on the name of the job on the next month and compare with Ucase of what worker entered. Though if the jobs panel didn't carry over to the next month then a new one would need to be created. 

3. If a new one would need to be created we would have to rework some of the guts of the script as it creates an income start date, if one is not entered, based on the footer month and year it finds on the panel it is on. (so if a new panel was made in 05/15 and a start income date wasn't entered by worker it would enter an income start date of 05/01/15 which actually doesn't cause an edit.)

So I guess before I proceed I just want to make sure this is state supported practice and if people think such an overhaul would be worth it. It would mostly be handy for cases that don't verify their income to avoid having to clear out stat edits for empty SNAP pics, incorrect dates, and HC income estimator. Though having to do these things does give the worker a bit more interaction with the case to make sure everything is correct. Thoughts?

**Comment by RoyStearns** [comment]
Been meaning to put this out there for this script for a while...I had some of the same issues where the job does not carry over to the new month. My thought was for the script to look at the lower left corner of Maxis for the "This data will expire xx-xx-date" to then do a warning to the worker so that you know it is not there. The worker can then create the panel by hand or alternatively put in the script to create the panel all over again in the new month if that message is seen.

On the side question- here we try to update it for the correct month, not just the future month as that helps with doing overpayments that may exist (since we are looking at FS as well as LTC, GA, MSA, GRH...which may have more strict reporting and OP policies) also you get all the income into the HC budg that should be there.

**Comment by theVKC** [comment]
:+1: to the "This data will expire xx-xx-date" idea.

I'm not sure we update the current month for overpayments every time right away. One of the dilemmas with this is that the "first paydate" is not always accurate in the report (it frequently is, but I digress). I believe as it currently stands, you CAN do this with New Job Reported (just put it in to the month the income came in, and it should carry over, unless the afore mentioned "This data will expire xx-xx-date" issue comes up). My interpretation has always been to go in during the footer month of the new HIRE message (each DAIL message has a footer month represented). 

I am open to re-evaluating that interpretation but I believe it's based on timeliness of report and the accuracy of the interface. And (lets face it), a lot of these folks didn't have to report it that first month anyway because the income never exceeded the minimum for reporting. So OPs aren't always the issue. But again, I'm open to re-evaluating. Let's keep discussing it. :)

**Comment by CDPotter** [comment]
@theVKC Since the scripts are working fine and the enhancement isn't really being clamored for maybe we just close this one for the time being?
