### ISSUE TITLE
CSES processing - CS arrears/current support for 18 yr old child in school

### ISSUE THREAD

**Issue by ALJ10** [MN-Script-Team/DHS-MAXIS-Scripts#568]
Here's an issue/policy clarification request from a supervisor:

There has been a question raised regarding the dail scrubber script. Policy for 18yr olds still in school receiving child support states to budget the income under them as their income. The dail scrubber puts the arrears under the appropriate children but not current support. 

Example: Two children in the hhld, one under 18 one over 18. The 18yr old is still in school and receiving child support along with the child under 18. The dail scrubber puts the current support for both children on the unea panel under the minor child, not the 18yr old and the other child. For SNAP this is ok because it is hhld income, but for HC this could be a problem. 

Thoughts?

**Comment by lpshanley** [comment]
Make the script scan for school status on 18yr olds and place the information accordingly ☺.

-Lucas
“Valar dohaeris”
#DecimateTheErrorRate
P Please consider the environment before printing this email. P

**Comment by theVKC** [comment]
Correct me if I’m wrong (because it’s been a LONG time since I looked into this), but for HC do we even care about updating it at all except for renewal? And… at renewal isn’t the instruction to evaluate several months’ worth to determine an amount, and not to insert last 30 days. I could be way off base, I haven’t worked in HC in a couple of years, and was an adult HC worker at that, so this rarely came up for me. I just remember that from building the script and getting business requirements 4 years ago.


Caution: This e-mail and attached documents, if any, may contain information that is protected by state or federal law. E-mail containing private or protected information should not be sent over a public (nonsecure) Internet unless it is encrypted pursuant to DHS standards. This e-mail should be forwarded only on a strictly need-to-know basis. If you are not the intended recipient, please: (1) notify the sender immediately, (2) do not forward the message, (3) do not print the message and (4) erase the message from your system.

**Comment by Farleight** [comment]
HC rules changed with the ACA. Since we're primarily using tax income for determinations now, CS doesn't count at all for any "MAGI" applicant. The non-MAGI cases (elderly/disabled) still use the old income rules. Though one can safely assume a 92 year old man probably isn't receiving Child Support, the same cannot necessarily be said for a disabled person. Regardless, any CS income placed in the UNEA panel at all for an HC case could potentially be a problem if we're not differentiating between the two groups.

**Comment by theVKC** [comment]
That makes sense. If I'm remembering correctly, it only adds it in for cash recipients. Does that sound right? That it isn't updating for HC?

**Comment by lpshanley** [comment]
HCPM Source is on the way ☺

-Lucas
“Valar dohaeris”
#DecimateTheErrorRate
P Please consider the environment before printing this email. P

**Comment by theVKC** [comment]
OK, I'm adding this to my to-do for this script. Based on the length of this to-do I might pound it out this weekend when I'm making up time from other non-work-related things. Yay flexible scheduling!

**Comment by theVKC** [comment]
Reassigned to @MelissaFox-Stearns! Good luck!
