### ISSUE TITLE
New Script - TYMA

### ISSUE THREAD

**Issue by lpshanley** [MN-Script-Team/DHS-MAXIS-Scripts#601]
A coworker approached me with the idea of making a script that would essentially create all the TIKL's related to the TYMA cases and then throw a case note on the case. I believe the essential idea is that it would scan the case to see if it is TYMA eligible and do the above actions accordingly. This should be a decently easy task to accomplish however my team is pretty far behind on documents at the moment and I just don't have the time to work on it. Anyone have any thoughts??

Edit 5/27/15:
The script will not need to scan the case this was a misunderstanding on my part. The script should simply set the TIKL's and place a CASE/NOTE after the worker has made the manual determination on the TYMA status. :smile: Hope that helps and sorry for any confusion.

**Comment by Farleight** [comment]
Yes... get caught up on documents. Seriously though, if anyone does this, keep in mind that the state has opted to allow anyone who potentially could be eligible for TYMA, to get it regardless of whether or not MAXIS views them as eligible. This was due to all the crazy workarounds we did last year screwing up the accuracy of MAXIS's detective skills in the matter. So at least for the time being, I'm not sure scanning the case to see if it's eligible would be the way to go... rather, I'd suggest you make it so a worker can manually input who is or is not eligible, and the script will blindly do as it's told without asking silly questions about whether or not it's proper, and it will smile at us when it's done, and it will like it.

**Comment by theVKC** [comment]
I'm marking this as "question" for now, because we probably want to resolve this sort of thing. @lpshanley, do you happen to already have a script made up for this?

**Comment by IlseFerris** [comment]
@LaLarson  or @ramonalisa1 Can you weigh in on this one?  I have limited family experience.

**Comment by LaLarson** [comment]
Okay... So in order to do the scanny type option, MAXIS/the script would need to be able to determine the following, and I'm not sure if MAXIS can do that at that at this point? Maybe a script could? Or maybe it could work like the expedited script, where you enter a bunch of criteria, and it determines if they are eligible or not, and then does all the TIKLing/CNing??

Here's the criteria:
1) Has the person been on MA for three of the last six months? 
2) Have they become ineligible for MA method A under the 133% FPG standard because of increased spousal support or earned income?
3) Do they have a parent/caretaker basis?
4) If they went over for increased spousal support (TMA), I guess they only get four months of additional eligibility? I don't know a lot about this, because I've never seen/done it, but that's my understanding. So that would have to be dealt with a little differently than TYMA.  Maybe it would be good to just start with TYMA.

Also... Just like @Farleight said, there were a lot of crazy work-arounds and PDED panels used for awhile there... This would only work if the case is all cleaned up.

It might just be better/more accurate for the worker to manually determine the eligibility for TYMA (or TMA), and to have a nice CN/TIKL script to just help with the end work?

That's what I've got?

**Comment by LaLarson** [comment]
I gotta say... Assuming that the case is clean/up to date in terms of income and deductions and all that... I kinda like the idea of a script that works like the expedited script! Answer the questions, and if it's the right answers it tells you that they appear eligible, and then does a CN and TIKL's!

**Comment by theVKC** [comment]
Thank you @LaLarson, for bringing the logic to my level. :)

I worry about a script's ability to figure out criteria 2 as laid out above. The others are easily coded but this one seems error prone for a script to figure out (to me, at least). I worry that a script to automatically do them all would be so full of "exceptions" that couldn't be determined, that it isn't worth the time in doing. But that's just me. I do love the idea of a CASE/NOTE and TIKL though. Love love love that. :+1:

**Comment by lpshanley** [comment]
I spoke with the worker who asked about the script and they said that all they would want it to is set all the TIKL's and place in a CASE/NOTE. She said it would be lovely if it could scan the case however that would be a request in the future if ever as scanning the case isn't time consuming its the time and repetition of the TIKL's and the CASE/NOTE that they would like to be sped up. So given my new understanding of the request, after the worker makes the TYMA determination then the script would set all the TIKL's and place a CASE/NOTE. I agree with everyone above that at this time scanning the case would be impractical. Given the update to the request what are peoples thoughts?

**Comment by lpshanley** [comment]
@theVKC no i currently have nothing written on this at the moment. Unfortunately this is the first time that I have been able to check this thread on git since I posted it. I keep tracking updates through my email however and I think, now that i have posted, these should go to my main inbox. I'll keep checking periodically to see any new posts. Thank you everyone!

**Comment by Farleight** [comment]
You have my support... cherish it.

**Comment by theVKC** [comment]
Closing due to lack of interest. I'm happy to reopen this if someone feels like working on it though.
