### ISSUE TITLE
Note - HH Comp Change - Power Pad option

### ISSUE THREAD

**Issue by GayS** [MN-Script-Team/DHS-MAXIS-Scripts#603]
The case note HH Comp Change isn't listed in the Power Pad Notes H-Z.

**Comment by theVKC** [comment]
That’s because it hasn’t been released yet. I didn’t do a May release because of other projects, and two mid-April bug fixes which through off the routine.


Caution: This e-mail and attached documents, if any, may contain information that is protected by state or federal law. E-mail containing private or protected information should not be sent over a public (nonsecure) Internet unless it is encrypted pursuant to DHS standards. This e-mail should be forwarded only on a strictly need-to-know basis. If you are not the intended recipient, please: (1) notify the sender immediately, (2) do not forward the message, (3) do not print the message and (4) erase the message from your system.

**Comment by GayS** [comment]
Ok - thanks
