### ISSUE TITLE
EDRS enhancement or new script -- "match found, what next?!"

### ISSUE THREAD

**Issue by IlseFerris** [MN-Script-Team/DHS-MAXIS-Scripts#881]
Requested from SIR.  Can EDRS case note when action was performed 

TE02.08.127 does NOT give information if this is something that should be case noted or not, only if there is a DISQ from another state.

@theVKC do you have any input?  Or @ruthmaloney?

**Comment by asunderman** [comment]
I can tell you that currently our Office Support person does a simple case note like “EDRS checked, no match” or if there is a match, she just casenotes that there was a match and that she printed off the info and gave it to the worker.  Pretty simple.

Ann

**Comment by ruthmaloney** [comment]
We review for this, but only call an error if there was an indication that the customer was open in another state (such as the CAF is marked, or information was given during the interview). If there was an indicator, we expect that the worker case notes the status in the other state and if there is an ABAWD that they check whether the customer has used an ABAWD months in the other state. If there is no indicator, we do not look into it any further.

I think it’s a good idea to have a script. Could it be an action script?

Ruth Maloney

**Comment by asunderman** [comment]
An action script would be GREAT!

**Comment by CDPotter** [comment]
When we originally made the ACTIONS - Check EDRS script the case noting side of things was left out because it was simply too difficult to program the script to determine if any hits found were still active or if they were even related. 

So for example you run the script on John Johnson and it comes up with countless hits from EDRS a script couldn't feasibly determine which of the many results actually relate to the client in question. 

We felt the best answer was to leave an findings to the worker to input. As such we added checkboxes for "checked EDRS" to a few of the scripts. My assumption is that if it simply says "checked EDRS" and nothing more then nothing was found. A worker should be case noting if they do find any results but automating that would be very difficult.

**Comment by RobertFewins-Kalb** [comment]
I agree. If there is a continued disqualification, the worker should be using NOTES - DENIED PROGRAMS for new applications and explain that the client has an eDRS match preventing them from SNAP eligibility.

**Comment by IlseFerris** [comment]
I will close this issue since there is nothing in policy that shows specifically that workers should be case noting the eDRS check when there is not a match, and denied programs should be used when closing a case for any reason. We can revisit this issue again if the policy changes.  Thanks everyone!

**Comment by IlseFerris** [comment]
OK, I'm going to reopen this.  How about a case note template similar to that of the CIT/ID where we can case note the eDRS action on HH members?  This has come up again at my county.

**Comment by theVKC** [comment]
If we could get consensus on what needs to be noted for eDRS (on a per-HH-memb-basis), I'm tentatively in favor of that move. @IlseFerris or @ruthmaloney or @asunderman, any ideas for what you might be looking for in your agencies?

**Comment by ruthmaloney** [comment]
It would be helpful to see something in a case note that it has been ran, for whom, and results.

Ruth Maloney

**Comment by IlseFerris** [comment]
Thanks for the feedback Ruth.  @theVKC go ahead and assign this one to me
