### ISSUE TITLE
Employment Verif Received has no field in the dialog for case number

### ISSUE THREAD

**Issue by RobertFewins-Kalb** [MN-Script-Team/DHS-MAXIS-Scripts#942]

**Comment by theVKC** [comment]
Are you on this? Or should I take it?

**Comment by RobertFewins-Kalb** [comment]
I'll take it

**Comment by theVKC** [comment]
Gotcha. Also: downgrading from critical because it's got the finder in it (you just need to start in a case). Can you pull this one into both master and BETA, because I already pulled the master change up.

**Comment by RobertFewins-Kalb** [comment]
yep

**Comment by theVKC** [comment]
Also, @StormageddonDLOA... this was your script, so just a friendly FYI in the future: we need a case_number editbox somewhere on the script so that way if you aren't in a MAXIS case (i.e. the SELF screen), it asks you to enter one. Still a great job for a first script, and my bad for not catching it during our training. :)

**Comment by theVKC** [comment]
Resolved with #946. @RobertFewins-Kalb, can you pull into BETA as well for testing?

**Comment by RobertFewins-Kalb** [comment]
Yes'um

**Comment by StormageddonDLOA** [comment]
Thanks for the heads up!

**Comment by theVKC** [comment]
Resolved with #946 and #947.
