### ISSUE TITLE
CSES dail scubber not calculating right?

### ISSUE THREAD

**Issue by CDPotter** [MN-Script-Team/DHS-MAXIS-Scripts#993]
I had a question about how the CSES dail scrubber calculates within the realm. After decoding it it looks like something must not be getting pulled through where it needs to be.

According to the worker her PIC was incorrect and she had to correct it. (case is privileged so I can't view it.)
Jun – was $709 and corrected to $756
Jul – was $756 and corrected to  $807
Aug – was $756 and corrected to $381 (this is the 1st month where it would have made a change to the elig amt, but the script said no change)
Sep – was $756 and corrected to $381

If the CSES_amt was 381 but the script still felt that was withing the realm (lowest - 10%) and (highest + 10%) or 638.1 through 831.6.

I'm not too familiar with the script as we don't get to use it in adult does anyone have time to review it in the immediate future?

**Comment by MelissaFox-Stearns** [comment]
I work with CS Dails quite a bit and use this scrubber a lot. 
Is she talking about the HC popup? because I'm pretty sure the scrubber doesn't update the FS PIC. 
The only time its updating, that I can tell, is when the case is MFIP or there is a HC Review due for that month. In these situations it updates the retro and prospective sides (and maybe the HC popup?). 

What would actually be SUPER helpful is if the script case noted the total amounts for CS and CS Arrears for each PMI for that month. This could be done as part of the automatic case note when the amounts are within the realm for FS, or when it is updated for MFIP or HC. 
Or in cases where the script tells you to process manually, it could do a msgbox with the totals before closing the script and excel doc. 

This gives the worker the information without having to spend the time adding all the amounts for each seperate PMI and each seperate type of CS (36 or 39) for that month. The worker could then determine if the totals are within the realm or should be plugged into the budget. 
My point of having the automatic case note indicate the amounts when the script says it is within range or has updated automatically would be so if it DOES go out of range, the worker can simply look back at the 3 months of the CS dail review totals and easily get an average if they need to.

I cannot stress how much time it takes to look back through 3 months of payments and separate the CS type and PMI and THEN get an average. So anything like this would be a huge huge help. 

I don't think I could tackle any modification of this script on my own (it is quite impressive) but I would love to collaborate if anyone felt so inclined.

**Comment by theVKC** [comment]
FYI: CSES script _DOES NOT_ code the SNAP PIC. At all. EVER. If the worker updated it they did this on their own, which is what they are supposed to do. SNAP "within the realm" in the script is defined as 10% higher than the highest amount on PIC, and 10% lower than the lowest. Anything within that is "within the realm" (which I calculated using statistics on manual updates of the PIC a few years ago, basically a BULK list gen in two different months and see which cases get manually updated).

I've been working on a mod to this script, but time has become too challenging for me to complete it. I was actually thinking of asking @courtrightd to take a look, owing to his status as a superstar, but I didn't want to intrude. I guess now I am... :P

**Comment by CDPotter** [comment]
That's what I had started to decipher from the code. I guess the claim is that the CSES amount was $381 for 2 kids and the highest pic amount was 756 and lowest 709. The sup who reported this said the worker has been getting messages that the CS is within the range (I'm guessing they mean the case notes) so somehow they are getting:

IF 381>=638 and 381<=831.6 then true (within realm)

Could just be user error? or maybe one of those goofy situations where a & is needed instead of and?

**Comment by theVKC** [comment]
Assigned this to @courtrightd only to make you aware. Closing the issue as I'm not convinced it's an issue.

**Comment by CDPotter** [comment]
@MelissaFox-Stearns @courtrightd A mentor at our county suggested that whomever is working on this rework the way within the realm is decided. They fear that the a 0 might be entered into the PIC thus making the lower part of the range 0. She suggested that the range be 10% below and above the average of whatever is in the PIC.

**Comment by MelissaFox-Stearns** [comment]
Some workers here at Stearns enter 0 on the PIC for one or more of the 3 months to get an average when a payment was skipped one month but then the client received a large amount in the next month. I've noticed we get quite a bit "Process Manually" messages when running the scrubber which could be the result of the script reading the 0 on the pic when determining within the realm. 
Reading from the average would probably get better results. 
@theVKC - would this change ruffle any feathers with the overlords?
